//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_PROVISIONAL_SALES
    {
        public string Transfer_No { get; set; }
        public Nullable<System.DateTime> Transfer_Date { get; set; }
        public string Vehicle_Code { get; set; }
        public string LoadOut_Location { get; set; }
        public string LoadIn_Location { get; set; }
        public string Salesmancode { get; set; }
        public string Emp_Name { get; set; }
        public string Item_Code { get; set; }
        public string Item_Desc { get; set; }
        public Nullable<decimal> LoadOutQty { get; set; }
        public Nullable<decimal> LoadInQty { get; set; }
        public Nullable<decimal> Conversion_Factor { get; set; }
        public string LoadIn_No { get; set; }
        public Nullable<decimal> Breakage { get; set; }
        public Nullable<decimal> Leak { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public string Unit_Code { get; set; }
        public string Vehicle_No { get; set; }
        public string Pack_Code { get; set; }
        public string Flavour_Code { get; set; }
        public decimal Amount { get; set; }
        public decimal Shortage { get; set; }
        public string RouteNo { get; set; }
        public decimal Loadout_Amount { get; set; }
        public decimal LoadOut_EmptyValue { get; set; }
        public decimal LoadIn_EmptyValue { get; set; }
        public string HOS { get; set; }
        public string TDM { get; set; }
        public string ADC { get; set; }
        public string CE { get; set; }
        public string Comp_Code { get; set; }
        public string Post { get; set; }
        public string Route_Type_Id { get; set; }
    }
}
