//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_REMITTANCE
    {
        public string Remittance_Code { get; set; }
        public string Remit_TDS { get; set; }
        public string Vendor_Code { get; set; }
        public string Vendor_Name { get; set; }
        public string Document_No { get; set; }
        public string Document_Date { get; set; }
        public string Document_Type { get; set; }
        public Nullable<decimal> Document_Amount { get; set; }
        public string Service_Type { get; set; }
        public Nullable<decimal> Actual_TDS_Base { get; set; }
        public Nullable<decimal> Calculated_TDS_Base { get; set; }
        public Nullable<decimal> Actual_TDS { get; set; }
        public Nullable<decimal> Calculated_TDS { get; set; }
        public Nullable<decimal> Actual_Surcharge { get; set; }
        public Nullable<decimal> Calculated_Surcharge { get; set; }
        public Nullable<decimal> Actual_Edu_Cess { get; set; }
        public Nullable<decimal> Calculated_Edu_Cess { get; set; }
        public Nullable<decimal> Actual_Sec_Educess { get; set; }
        public Nullable<decimal> Calculated_Sec_Educess { get; set; }
        public Nullable<decimal> Actual_Total_TDS { get; set; }
        public Nullable<decimal> Calculated_Total_TDS { get; set; }
        public string Section_Code { get; set; }
        public string Section_Description { get; set; }
        public string Branch_Code { get; set; }
        public string Select_By { get; set; }
        public string Created_By { get; set; }
        public string Created_Date { get; set; }
        public string Modify_By { get; set; }
        public string Modify_Date { get; set; }
        public string Comp_Code { get; set; }
        public Nullable<decimal> TDS_Per { get; set; }
        public Nullable<decimal> Surcharge_Per { get; set; }
        public Nullable<decimal> Edu_Cess_Per { get; set; }
        public Nullable<decimal> Sec_Educess_Per { get; set; }
        public string Fiscal_Year { get; set; }
        public string Quarter { get; set; }
        public string Deduction_Code { get; set; }
        public string Branch_GL_AC { get; set; }
        public string Remittance_Main_Code { get; set; }
        public string Vendor_Invoice_No { get; set; }
        public Nullable<decimal> Previous_TDS_Amt { get; set; }
        public int Is_TDS_Override { get; set; }
        public string Is_TDS_Provision { get; set; }
    
        public virtual TSPL_GL_ACCOUNTS TSPL_GL_ACCOUNTS { get; set; }
        public virtual TSPL_TDS_DEDUCTION_HEAD TSPL_TDS_DEDUCTION_HEAD { get; set; }
    }
}
