//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_VISI_INSTALL_PULLOUT
    {
        public string Visi_Id { get; set; }
        public string VisiMake { get; set; }
        public Nullable<System.DateTime> Visi_Installation_date { get; set; }
        public string Customer_Id { get; set; }
        public string Customer_name { get; set; }
        public string Asset_No { get; set; }
        public string Visi_Size { get; set; }
        public string Visi_Chasis_No { get; set; }
        public string Model_No { get; set; }
        public string Type { get; set; }
        public string Location { get; set; }
        public string Route { get; set; }
        public Nullable<System.DateTime> Pull_Out_Date { get; set; }
        public Nullable<int> Row_No { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Modified_By { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public string Comp_Code { get; set; }
        public string Trans_Type { get; set; }
        public string Visi_Type { get; set; }
        public System.DateTime Trans_Date { get; set; }
    }
}
