//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_SALES_ORDER_MASTER_BULKSALE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSPL_SALES_ORDER_MASTER_BULKSALE()
        {
            this.TSPL_Dispatch_BulkSale = new HashSet<TSPL_Dispatch_BulkSale>();
            this.TSPL_GATEENTRY_SALE = new HashSet<TSPL_GATEENTRY_SALE>();
            this.TSPL_GATEOUT_SALE = new HashSet<TSPL_GATEOUT_SALE>();
            this.TSPL_LOADING_TANKER_DETAIL_BULKSALE = new HashSet<TSPL_LOADING_TANKER_DETAIL_BULKSALE>();
            this.TSPL_Quality_Check_BulkSale = new HashSet<TSPL_Quality_Check_BulkSale>();
            this.TSPL_SALES_ORDER_DETAIL_BULKSALE = new HashSet<TSPL_SALES_ORDER_DETAIL_BULKSALE>();
            this.TSPL_WEIGHMENT_DETAIL_BULKSALE = new HashSet<TSPL_WEIGHMENT_DETAIL_BULKSALE>();
        }
    
        public string Document_No { get; set; }
        public System.DateTime Document_Date { get; set; }
        public string Customer_Code { get; set; }
        public string Customer_Name { get; set; }
        public string Location_Code { get; set; }
        public string Location_Name { get; set; }
        public string TERMS_Code { get; set; }
        public string PO_NO { get; set; }
        public System.DateTime PO_Date { get; set; }
        public string Price_Code { get; set; }
        public decimal Fat_Weightage { get; set; }
        public decimal Snf_Weightage { get; set; }
        public decimal Fat_Ratio { get; set; }
        public decimal Snf_Ratio { get; set; }
        public decimal Standard_Rate { get; set; }
        public double TolerancePerPlus { get; set; }
        public double TolerancePerMinus { get; set; }
        public int Posted { get; set; }
        public Nullable<System.DateTime> Posting_Date { get; set; }
        public string Comp_Code { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Modified_By { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public double DocumentAmount { get; set; }
        public string close_remarks { get; set; }
        public string Closed_By { get; set; }
        public Nullable<System.DateTime> Closed_Date { get; set; }
        public string close_yn { get; set; }
    
        public virtual TSPL_BulkSalePrice_MASTER TSPL_BulkSalePrice_MASTER { get; set; }
        public virtual TSPL_CUSTOMER_MASTER TSPL_CUSTOMER_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_Dispatch_BulkSale> TSPL_Dispatch_BulkSale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_GATEENTRY_SALE> TSPL_GATEENTRY_SALE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_GATEOUT_SALE> TSPL_GATEOUT_SALE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_LOADING_TANKER_DETAIL_BULKSALE> TSPL_LOADING_TANKER_DETAIL_BULKSALE { get; set; }
        public virtual TSPL_LOCATION_MASTER TSPL_LOCATION_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_Quality_Check_BulkSale> TSPL_Quality_Check_BulkSale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_SALES_ORDER_DETAIL_BULKSALE> TSPL_SALES_ORDER_DETAIL_BULKSALE { get; set; }
        public virtual TSPL_TERMS_MASTER TSPL_TERMS_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_WEIGHMENT_DETAIL_BULKSALE> TSPL_WEIGHMENT_DETAIL_BULKSALE { get; set; }
    }
}
