//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_TDS_PAYMENT_DETAIL
    {
        public string Document_No { get; set; }
        public string Document_type { get; set; }
        public string TDS_Deduction_Code { get; set; }
        public string Vendor_Code { get; set; }
        public string Against_Document_No { get; set; }
        public System.DateTime Against_Document_Date { get; set; }
        public string PAN { get; set; }
        public double Taxable_Amount { get; set; }
        public double Document_amount { get; set; }
        public double Income_tax { get; set; }
        public double TotalTdsAmount { get; set; }
        public double RateForTdsDeduction { get; set; }
        public string Location_Code { get; set; }
        public string Deduct_Code { get; set; }
        public string Description { get; set; }
        public string GL_Account { get; set; }
    
        public virtual TSPL_TDS_DEDUCTION_HEAD TSPL_TDS_DEDUCTION_HEAD { get; set; }
        public virtual TSPL_TDS_PAYMENT_HEADER TSPL_TDS_PAYMENT_HEADER { get; set; }
        public virtual TSPL_VENDOR_MASTER TSPL_VENDOR_MASTER { get; set; }
    }
}
