//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_VILLAGE_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSPL_VILLAGE_MASTER()
        {
            this.TSPL_VLC_MASTER_DETAIL = new HashSet<TSPL_VLC_MASTER_DETAIL>();
            this.TSPL_VLC_MASTER_HEAD = new HashSet<TSPL_VLC_MASTER_HEAD>();
        }
    
        public string Village_Code { get; set; }
        public string Village_Name { get; set; }
        public string Add1 { get; set; }
        public string Add2 { get; set; }
        public string City_Code { get; set; }
        public string State_Code { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string PIN_NO { get; set; }
        public string Created_By { get; set; }
        public string Created_Date { get; set; }
        public string Modified_By { get; set; }
        public string Modified_Date { get; set; }
        public string comp_code { get; set; }
        public string Surveyor_Name { get; set; }
        public Nullable<System.DateTime> Survey_Date { get; set; }
        public Nullable<decimal> Total_Population { get; set; }
        public string Tehsil { get; set; }
        public Nullable<decimal> Total_Voting { get; set; }
        public string Pradhan_Name { get; set; }
        public string Pradhan_Contact_No { get; set; }
        public Nullable<decimal> Distance_From_Center { get; set; }
        public string Irrigation_Source { get; set; }
        public string Village_Area { get; set; }
        public Nullable<decimal> Distance_From_MCC { get; set; }
        public Nullable<decimal> Cow_In_Milk { get; set; }
        public Nullable<decimal> Buffalo_In_Milk { get; set; }
        public Nullable<decimal> Cow_Dry { get; set; }
        public Nullable<decimal> Buffalo_Dry { get; set; }
        public Nullable<decimal> Total_Animals { get; set; }
        public Nullable<decimal> Milk_Production_Per_Day_Cow { get; set; }
        public Nullable<decimal> Milk_Production_Per_Day_Buffalo { get; set; }
        public Nullable<decimal> Marketable_Surplus_Per_Day_Cow { get; set; }
        public Nullable<decimal> Marketable_Surplus_Per_Day_Buffalo { get; set; }
        public Nullable<decimal> Expected_Milk_Per_Day_Cow { get; set; }
        public Nullable<decimal> Expected_Milk_Per_Day_Buffalo { get; set; }
        public string Village_Name_Hindi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_VLC_MASTER_DETAIL> TSPL_VLC_MASTER_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_VLC_MASTER_HEAD> TSPL_VLC_MASTER_HEAD { get; set; }
    }
}
