//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_PAYMENT_PROCESS_INVOICE
    {
        public string Doc_No { get; set; }
        public string SLNO { get; set; }
        public string Milk_Purchase_Invoice_No { get; set; }
        public string Milk_Purchase_Invoice_Date { get; set; }
        public string AP_Invoice_No { get; set; }
        public string AP_Invoice_Date { get; set; }
        public string VLC_CODE { get; set; }
        public string VSP_CODE { get; set; }
        public string VSP_NAME { get; set; }
        public string Payee_Joint_Name { get; set; }
        public string Payee_Joint_Ac_No { get; set; }
        public string Payee_Joint_Bank_Code { get; set; }
        public string Payee_Joint_Bank_Name { get; set; }
        public string Payee_Joint_Branch_Code { get; set; }
        public string Payee_Joint_Branch_Name { get; set; }
        public string Payee_Joint_IFSC_Code { get; set; }
        public double Milk_Qty { get; set; }
        public double Inv_Amount { get; set; }
        public double Inv_EMP_Amount { get; set; }
        public double Inv_Amt_EMP_Amount { get; set; }
        public double Inv_Incentive_Amount { get; set; }
        public double Inv_Incentive_EMP_Amount { get; set; }
        public double Gross_Amount { get; set; }
        public double Vsp_Own_System_Amount { get; set; }
        public double Head_Load_Amount { get; set; }
        public double Deduction_Amount { get; set; }
        public string Vsp_Own_System_Doc_No { get; set; }
        public string Head_Load_Doc_No { get; set; }
        public string Deduction_Doc_No { get; set; }
        public double Reduce_Deduc_Amt { get; set; }
        public string Bank_Code { get; set; }
        public string Bank_Desc { get; set; }
        public string Payment_Mode { get; set; }
        public string Cheque_No { get; set; }
        public double Service_Charge_Amt { get; set; }
        public Nullable<decimal> MP_Amount { get; set; }
        public Nullable<decimal> MP_EMP { get; set; }
        public Nullable<decimal> MP_Incentive { get; set; }
        public Nullable<decimal> MP_IncentiveEMP { get; set; }
        public Nullable<decimal> MP_Net_Amount { get; set; }
        public Nullable<decimal> Handling_Charges_Amount { get; set; }
        public Nullable<decimal> SRN_Net_Amount { get; set; }
        public Nullable<decimal> SRN_RO_Amount { get; set; }
        public string MCC_Code { get; set; }
        public Nullable<decimal> TDS_Amount { get; set; }
    
        public virtual TSPL_MCC_MASTER TSPL_MCC_MASTER { get; set; }
    }
}
