//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_STANDARD_SCHEME
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSPL_STANDARD_SCHEME()
        {
            this.TSPL_STANDARD_SCHEME_DETAIL = new HashSet<TSPL_STANDARD_SCHEME_DETAIL>();
        }
    
        public string StdSchCode { get; set; }
        public System.DateTime FomeDate { get; set; }
        public Nullable<System.DateTime> Valied_Date { get; set; }
        public Nullable<bool> IsValied_Date { get; set; }
        public string Cust_Code { get; set; }
        public string Descraption { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Modified_By { get; set; }
        public System.DateTime Modified_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_STANDARD_SCHEME_DETAIL> TSPL_STANDARD_SCHEME_DETAIL { get; set; }
    }
}
