//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_CANCEL_CONDITION_TABLES_DETAILS
    {
        public string Form_Id { get; set; }
        public int Base_Level_Id { get; set; }
        public string Condition_tb_name { get; set; }
        public string Condition_Col_Name { get; set; }
        public string Condition_Foreign_Col_Name { get; set; }
        public int Condition_Level_Id { get; set; }
        public string Type_Col_Name { get; set; }
        public string Type_Col_Value { get; set; }
        public string Is_For_validate { get; set; }
    }
}
