//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_DCS_FINANCIAL_ENTRY_DETAIL
    {
        public int PK_Id { get; set; }
        public string Document_Code { get; set; }
        public Nullable<decimal> SNo1 { get; set; }
        public string Head_Code1 { get; set; }
        public Nullable<int> Amount_Type1 { get; set; }
        public Nullable<decimal> Head_Sub_Amount1 { get; set; }
        public Nullable<decimal> Head_Amount1 { get; set; }
        public Nullable<decimal> SNo2 { get; set; }
        public string Head_Code2 { get; set; }
        public Nullable<int> Amount_Type2 { get; set; }
        public Nullable<decimal> Head_Sub_Amount2 { get; set; }
        public Nullable<decimal> Head_Amount2 { get; set; }
    
        public virtual TSPL_DCS_FINANCIAL_ENTRY TSPL_DCS_FINANCIAL_ENTRY { get; set; }
        public virtual TSPL_DCS_FINANCIAL_HEAD TSPL_DCS_FINANCIAL_HEAD { get; set; }
        public virtual TSPL_DCS_FINANCIAL_HEAD TSPL_DCS_FINANCIAL_HEAD1 { get; set; }
    }
}
