//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_OWN_BMC_EXPANSE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSPL_OWN_BMC_EXPANSE()
        {
            this.TSPL_MILK_PURCHASE_INVOICE_OWN_BMC_EXPANSE = new HashSet<TSPL_MILK_PURCHASE_INVOICE_OWN_BMC_EXPANSE>();
            this.TSPL_OWN_BMC_EXPANSE_SLAB = new HashSet<TSPL_OWN_BMC_EXPANSE_SLAB>();
        }
    
        public string Code { get; set; }
        public string Description { get; set; }
        public System.DateTime Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public decimal FAT { get; set; }
        public decimal SNF { get; set; }
        public decimal Rate { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Modified_By { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public int Posted { get; set; }
        public string Posted_By { get; set; }
        public Nullable<System.DateTime> Posted_Date { get; set; }
        public int Inactive { get; set; }
        public string Inactive_By { get; set; }
        public Nullable<System.DateTime> Inactive_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MILK_PURCHASE_INVOICE_OWN_BMC_EXPANSE> TSPL_MILK_PURCHASE_INVOICE_OWN_BMC_EXPANSE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_OWN_BMC_EXPANSE_SLAB> TSPL_OWN_BMC_EXPANSE_SLAB { get; set; }
    }
}
