//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_SYNC_HEAD_TBL
    {
        public string TABLE_NAME { get; set; }
        public string KEY_COLUMN { get; set; }
        public string DATE_COLUMN { get; set; }
        public string MCC_COLUMN { get; set; }
        public int SEQ_NO { get; set; }
        public string SYNC_TEMP_TABLE { get; set; }
        public string SYNC_TYPE { get; set; }
        public string KEY_COLUMN_2 { get; set; }
        public string KEY_COLUMN_3 { get; set; }
        public string SHIFT_COLUMN { get; set; }
        public Nullable<int> SYNC_START_FLAG { get; set; }
    }
}
