//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_TRANSACTION_REVERSE_LOG
    {
        public int LOG_ID { get; set; }
        public string Program_Code { get; set; }
        public string DOCUMENT_NO { get; set; }
        public string REASON { get; set; }
        public System.DateTime REVERSE_DATE { get; set; }
        public string ACTIVITY_TYPE { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Modified_By { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public string Doc_Created_By { get; set; }
        public Nullable<System.DateTime> Doc_Created_Date { get; set; }
        public string Doc_Posted_By { get; set; }
        public Nullable<System.DateTime> Doc_Posted_Date { get; set; }
    
        public virtual TSPL_PROGRAM_MASTER TSPL_PROGRAM_MASTER { get; set; }
    }
}
