//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_PT_DETAIL
    {
        public string PT_CODE { get; set; }
        public decimal SLAB_FROM { get; set; }
        public decimal SLAB_TO { get; set; }
        public decimal PT_AMOUNT { get; set; }
    
        public virtual TSPL_PT_RULE_MASTER TSPL_PT_RULE_MASTER { get; set; }
    }
}
