//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_INVOICE_CRATE_LINER_HEAD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSPL_INVOICE_CRATE_LINER_HEAD()
        {
            this.TSPL_INVOICE_CRATE_LINER_DETAIL = new HashSet<TSPL_INVOICE_CRATE_LINER_DETAIL>();
        }
    
        public string DOCUMENT_NO { get; set; }
        public System.DateTime DOCUMENT_DATE { get; set; }
        public string LOCATION_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFY_BY { get; set; }
        public System.DateTime MODIFY_DATE { get; set; }
        public int POSTED { get; set; }
        public string POSTED_BY { get; set; }
        public Nullable<System.DateTime> POSTED_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_INVOICE_CRATE_LINER_DETAIL> TSPL_INVOICE_CRATE_LINER_DETAIL { get; set; }
    }
}
