//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_Additional_Charges
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSPL_Additional_Charges()
        {
            this.TSPL_GRN_ADDITION_CHARGE_INSURANCE = new HashSet<TSPL_GRN_ADDITION_CHARGE_INSURANCE>();
            this.TSPL_MRN_ADDITION_CHARGE_INSURANCE = new HashSet<TSPL_MRN_ADDITION_CHARGE_INSURANCE>();
            this.TSPL_PI_ADDITION_CHARGE_INSURANCE = new HashSet<TSPL_PI_ADDITION_CHARGE_INSURANCE>();
            this.TSPL_PR_ADDITION_CHARGE_INSURANCE = new HashSet<TSPL_PR_ADDITION_CHARGE_INSURANCE>();
            this.TSPL_PURCHASE_ORDER_ADDITION_CHARGE_INSURANCE = new HashSet<TSPL_PURCHASE_ORDER_ADDITION_CHARGE_INSURANCE>();
            this.TSPL_SRN_ADDITION_CHARGE_INSURANCE = new HashSet<TSPL_SRN_ADDITION_CHARGE_INSURANCE>();
        }
    
        public string Code { get; set; }
        public string Description { get; set; }
        public string Created_By { get; set; }
        public string Created_Date { get; set; }
        public string Modified_By { get; set; }
        public string Modified_Date { get; set; }
        public string Comp_Code { get; set; }
        public string Account_Code { get; set; }
        public string Account_Description { get; set; }
        public string FreightCharges { get; set; }
        public Nullable<double> abatement { get; set; }
        public string specification { get; set; }
        public Nullable<double> Reverse_Charge_Per { get; set; }
        public string Service_Type { get; set; }
        public string SAC_Code { get; set; }
        public int RCM { get; set; }
        public int NO_GST_Credit { get; set; }
        public Nullable<int> Is_Insurance { get; set; }
        public Nullable<int> Is_RoundOff { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_GRN_ADDITION_CHARGE_INSURANCE> TSPL_GRN_ADDITION_CHARGE_INSURANCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MRN_ADDITION_CHARGE_INSURANCE> TSPL_MRN_ADDITION_CHARGE_INSURANCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PI_ADDITION_CHARGE_INSURANCE> TSPL_PI_ADDITION_CHARGE_INSURANCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PR_ADDITION_CHARGE_INSURANCE> TSPL_PR_ADDITION_CHARGE_INSURANCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PURCHASE_ORDER_ADDITION_CHARGE_INSURANCE> TSPL_PURCHASE_ORDER_ADDITION_CHARGE_INSURANCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_SRN_ADDITION_CHARGE_INSURANCE> TSPL_SRN_ADDITION_CHARGE_INSURANCE { get; set; }
    }
}
