//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_RECEIPT_HEADER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSPL_RECEIPT_HEADER()
        {
            this.TSPL_BOOKING_MATSER = new HashSet<TSPL_BOOKING_MATSER>();
            this.TSPL_BOOKING_PAYMENT_MODE_DETAIL = new HashSet<TSPL_BOOKING_PAYMENT_MODE_DETAIL>();
            this.TSPL_Customer_Invoice_Head = new HashSet<TSPL_Customer_Invoice_Head>();
            this.TSPL_RECEIPT_DETAIL_REFUND = new HashSet<TSPL_RECEIPT_DETAIL_REFUND>();
            this.TSPL_RECEIPT_DETAIL_GST = new HashSet<TSPL_RECEIPT_DETAIL_GST>();
            this.TSPL_RECEIPT_INVOICEMAPPING_HEAD = new HashSet<TSPL_RECEIPT_INVOICEMAPPING_HEAD>();
            this.TSPL_REVALUATION_DETAIL = new HashSet<TSPL_REVALUATION_DETAIL>();
            this.TSPL_THIRD_PARTY_RECEIPT_ENTRY = new HashSet<TSPL_THIRD_PARTY_RECEIPT_ENTRY>();
            this.TSPL_WS_CARD_SALE_MASTER = new HashSet<TSPL_WS_CARD_SALE_MASTER>();
        }
    
        public string Receipt_No { get; set; }
        public Nullable<System.DateTime> Receipt_Date { get; set; }
        public Nullable<System.DateTime> Receipt_Post_Date { get; set; }
        public string Entry_Desc { get; set; }
        public string Bank_Code { get; set; }
        public string Receipt_Type { get; set; }
        public string Cust_Code { get; set; }
        public string Customer_Name { get; set; }
        public string Reference { get; set; }
        public string Narration { get; set; }
        public string Payment_Code { get; set; }
        public string Cheque_No { get; set; }
        public string Cheque_Date { get; set; }
        public decimal Receipt_Amount { get; set; }
        public string Cust_Account { get; set; }
        public string Apply_By { get; set; }
        public string Apply_To { get; set; }
        public string Posted { get; set; }
        public string Created_By { get; set; }
        public string Created_Date { get; set; }
        public string Modify_By { get; set; }
        public string Modify_Date { get; set; }
        public string Level1_User_code { get; set; }
        public string Level2_User_code { get; set; }
        public string Level3_User_code { get; set; }
        public string Level4_User_code { get; set; }
        public string Level5_User_code { get; set; }
        public string Comp_Code { get; set; }
        public Nullable<decimal> Balance_Amt { get; set; }
        public string Document_No { get; set; }
        public Nullable<decimal> UnApply_Amt { get; set; }
        public string Payer { get; set; }
        public string Dr_Account { get; set; }
        public string Cr_Account { get; set; }
        public Nullable<decimal> UnApplied_Balance { get; set; }
        public string UnApplied_No { get; set; }
        public decimal FIFO_Balance { get; set; }
        public string QuickEntryNo { get; set; }
        public string SecurityDeposit { get; set; }
        public string IsRecoCleared { get; set; }
        public string IsChkReverse { get; set; }
        public string IsSalesmanType { get; set; }
        public string Salesman_Code { get; set; }
        public string Salesman_Name { get; set; }
        public string Loadout_No { get; set; }
        public string Cheque_From { get; set; }
        public string CURRENCY_CODE { get; set; }
        public Nullable<decimal> ConvRate { get; set; }
        public Nullable<System.DateTime> ApplicableFrom { get; set; }
        public string CFormRecd { get; set; }
        public string CForm_InvoiceNo { get; set; }
        public string BASE_CURRENCY_CODE { get; set; }
        public decimal RECEIVED_AMOUNT_BASE_CURRENCY { get; set; }
        public decimal EXCHANGE_LOSS_AMT { get; set; }
        public decimal EXCHANGE_GAIN_AMT { get; set; }
        public string EXCHANGE_LOSS_ACCOUNT { get; set; }
        public string EXCHANGE_GAIN_ACCOUNT { get; set; }
        public decimal ConvRateOld { get; set; }
        public string PROJECT_ID { get; set; }
        public int IsParentCust { get; set; }
        public int CHECK_PRINT { get; set; }
        public string CHECK_CODE { get; set; }
        public bool AUTO_GEN_BT_ENTRY { get; set; }
        public string TO_BANK_CODE { get; set; }
        public string Transfer_No { get; set; }
        public string From_Branch { get; set; }
        public double memorandum_amt { get; set; }
        public string Applied_Receipt { get; set; }
        public string SecurityDepositType { get; set; }
        public string SaleOrderNo { get; set; }
        public string Against_CSA_Transfer_Code { get; set; }
        public string Booking_Code { get; set; }
        public string Location_GL_Code { get; set; }
        public int is_Opening { get; set; }
        public double Foreign_Bank_Charges_Amt { get; set; }
        public double Bank_Charges_Amt { get; set; }
        public string OTP { get; set; }
        public string Distr_Code { get; set; }
        public int IsApplyDocAuto { get; set; }
        public string Delivery_Code_PS { get; set; }
        public string Tax_Group { get; set; }
        public double Delivery_order_Amount { get; set; }
        public double Tax_Amount_Advance { get; set; }
        public double DO_Total_Add_Amount { get; set; }
        public string TAX1 { get; set; }
        public Nullable<decimal> TAX1_Base_Amt { get; set; }
        public Nullable<decimal> TAX1_Rate { get; set; }
        public Nullable<decimal> TAX1_Amt { get; set; }
        public string TAX2 { get; set; }
        public Nullable<decimal> TAX2_Base_Amt { get; set; }
        public Nullable<decimal> TAX2_Rate { get; set; }
        public Nullable<decimal> TAX2_Amt { get; set; }
        public string TAX3 { get; set; }
        public Nullable<decimal> TAX3_Base_Amt { get; set; }
        public Nullable<decimal> TAX3_Rate { get; set; }
        public Nullable<decimal> TAX3_Amt { get; set; }
        public string TAX4 { get; set; }
        public Nullable<decimal> TAX4_Base_Amt { get; set; }
        public Nullable<decimal> TAX4_Rate { get; set; }
        public Nullable<decimal> TAX4_Amt { get; set; }
        public string TAX5 { get; set; }
        public Nullable<decimal> TAX5_Base_Amt { get; set; }
        public Nullable<decimal> TAX5_Rate { get; set; }
        public Nullable<decimal> TAX5_Amt { get; set; }
        public string TAX6 { get; set; }
        public Nullable<decimal> TAX6_Base_Amt { get; set; }
        public Nullable<decimal> TAX6_Rate { get; set; }
        public Nullable<decimal> TAX6_Amt { get; set; }
        public string TAX7 { get; set; }
        public Nullable<decimal> TAX7_Base_Amt { get; set; }
        public Nullable<decimal> TAX7_Rate { get; set; }
        public Nullable<decimal> TAX7_Amt { get; set; }
        public string TAX8 { get; set; }
        public Nullable<decimal> TAX8_Base_Amt { get; set; }
        public Nullable<decimal> TAX8_Rate { get; set; }
        public Nullable<decimal> TAX8_Amt { get; set; }
        public string TAX9 { get; set; }
        public Nullable<decimal> TAX9_Base_Amt { get; set; }
        public Nullable<decimal> TAX9_Rate { get; set; }
        public Nullable<decimal> TAX9_Amt { get; set; }
        public string TAX10 { get; set; }
        public Nullable<decimal> TAX10_Base_Amt { get; set; }
        public Nullable<decimal> TAX10_Rate { get; set; }
        public Nullable<decimal> TAX10_Amt { get; set; }
        public string SO_Location_Code { get; set; }
        public string ReceiptAgainstSO_DO { get; set; }
        public string cheque_in_favour_of { get; set; }
        public Nullable<int> AC_Payee { get; set; }
        public Nullable<System.DateTime> Set_Off_Date { get; set; }
        public Nullable<bool> SetOffSkipJE { get; set; }
        public int IsAutoApplyDoc_Refund { get; set; }
        public Nullable<System.DateTime> DateAndTime { get; set; }
        public string TapalNo { get; set; }
        public string Rec_Route_Code { get; set; }
        public string Rec_Zone_Code { get; set; }
        public int isCardSale { get; set; }
        public string Against_RCDF_Loadin { get; set; }
    
        public virtual TSPL_BANK_CHECK_PRINTING TSPL_BANK_CHECK_PRINTING { get; set; }
        public virtual TSPL_BANK_MASTER TSPL_BANK_MASTER { get; set; }
        public virtual TSPL_BANK_MASTER TSPL_BANK_MASTER1 { get; set; }
        public virtual TSPL_BANK_TRANSFER TSPL_BANK_TRANSFER { get; set; }
        public virtual TSPL_BOOKING_MASTER_PRODUCTSALE TSPL_BOOKING_MASTER_PRODUCTSALE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_BOOKING_MATSER> TSPL_BOOKING_MATSER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_BOOKING_PAYMENT_MODE_DETAIL> TSPL_BOOKING_PAYMENT_MODE_DETAIL { get; set; }
        public virtual TSPL_CURRENCY_MASTER TSPL_CURRENCY_MASTER { get; set; }
        public virtual TSPL_CURRENCY_MASTER TSPL_CURRENCY_MASTER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_Customer_Invoice_Head> TSPL_Customer_Invoice_Head { get; set; }
        public virtual TSPL_GL_ACCOUNTS TSPL_GL_ACCOUNTS { get; set; }
        public virtual TSPL_GL_ACCOUNTS TSPL_GL_ACCOUNTS1 { get; set; }
        public virtual TSPL_LOCATION_MASTER TSPL_LOCATION_MASTER { get; set; }
        public virtual TSPL_PJC_PROJECT TSPL_PJC_PROJECT { get; set; }
        public virtual TSPL_RCDF_LOAD_IN TSPL_RCDF_LOAD_IN { get; set; }
        public virtual TSPL_SECONDARY_CUSTOMER_MASTER TSPL_SECONDARY_CUSTOMER_MASTER { get; set; }
        public virtual TSPL_ROUTE_MASTER TSPL_ROUTE_MASTER { get; set; }
        public virtual TSPL_ZONE_MASTER TSPL_ZONE_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_RECEIPT_DETAIL_REFUND> TSPL_RECEIPT_DETAIL_REFUND { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_RECEIPT_DETAIL_GST> TSPL_RECEIPT_DETAIL_GST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_RECEIPT_INVOICEMAPPING_HEAD> TSPL_RECEIPT_INVOICEMAPPING_HEAD { get; set; }
        public virtual TSPL_SD_SALES_ORDER_HEAD TSPL_SD_SALES_ORDER_HEAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_REVALUATION_DETAIL> TSPL_REVALUATION_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_THIRD_PARTY_RECEIPT_ENTRY> TSPL_THIRD_PARTY_RECEIPT_ENTRY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_WS_CARD_SALE_MASTER> TSPL_WS_CARD_SALE_MASTER { get; set; }
    }
}
