//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_GL_STRUCTURE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSPL_GL_STRUCTURE()
        {
            this.TSPL_GL_ACCOUNTS = new HashSet<TSPL_GL_ACCOUNTS>();
        }
    
        public string Str_Code { get; set; }
        public string Str_Description { get; set; }
        public string Default_Structure { get; set; }
        public Nullable<int> Seg_No1 { get; set; }
        public string Seg_Name1 { get; set; }
        public Nullable<int> Seg_length1 { get; set; }
        public Nullable<int> Seg_No2 { get; set; }
        public string Seg_Name2 { get; set; }
        public Nullable<int> Seg_length2 { get; set; }
        public Nullable<int> Seg_No3 { get; set; }
        public string Seg_Name3 { get; set; }
        public Nullable<int> Seg_length3 { get; set; }
        public Nullable<int> Seg_No4 { get; set; }
        public string Seg_Name4 { get; set; }
        public Nullable<int> Seg_length4 { get; set; }
        public Nullable<int> Seg_No5 { get; set; }
        public string Seg_Name5 { get; set; }
        public Nullable<int> Seg_length5 { get; set; }
        public Nullable<int> Seg_No6 { get; set; }
        public string Seg_Name6 { get; set; }
        public Nullable<int> Seg_length6 { get; set; }
        public Nullable<int> Seg_No7 { get; set; }
        public string Seg_Name7 { get; set; }
        public Nullable<int> Seg_length7 { get; set; }
        public Nullable<int> Seg_No8 { get; set; }
        public string Seg_Name8 { get; set; }
        public Nullable<int> Seg_length8 { get; set; }
        public Nullable<int> Seg_No9 { get; set; }
        public string Seg_Name9 { get; set; }
        public Nullable<int> Seg_length9 { get; set; }
        public Nullable<int> Seg_No10 { get; set; }
        public string Seg_Name10 { get; set; }
        public Nullable<int> Seg_length10 { get; set; }
        public string Created_By { get; set; }
        public string Created_Date { get; set; }
        public string Modify_By { get; set; }
        public string Modify_Date { get; set; }
        public string Comp_Code { get; set; }
    
        public virtual TSPL_COMPANY_MASTER TSPL_COMPANY_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_GL_ACCOUNTS> TSPL_GL_ACCOUNTS { get; set; }
    }
}
