//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_SHIFT_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSPL_SHIFT_MASTER()
        {
            this.TSPL_EMPLOYEE_MASTER = new HashSet<TSPL_EMPLOYEE_MASTER>();
            this.TSPL_EMPLOYEE_STATUS = new HashSet<TSPL_EMPLOYEE_STATUS>();
            this.TSPL_PRODUCTION_UPLOADER_DETAIL = new HashSet<TSPL_PRODUCTION_UPLOADER_DETAIL>();
            this.TSPL_EMPLOYEE_SHIFT_CHANGE_DETAIL = new HashSet<TSPL_EMPLOYEE_SHIFT_CHANGE_DETAIL>();
            this.TSPL_PE_FINALQC_DETAIL = new HashSet<TSPL_PE_FINALQC_DETAIL>();
            this.TSPL_PP_BATCH_ITEM_PRODUCTION_DETAIL = new HashSet<TSPL_PP_BATCH_ITEM_PRODUCTION_DETAIL>();
            this.TSPL_PP_BATCH_ORDER_BOM_DETAIL = new HashSet<TSPL_PP_BATCH_ORDER_BOM_DETAIL>();
            this.TSPL_PP_PRODUCTION_ENTRY_DETAIL = new HashSet<TSPL_PP_PRODUCTION_ENTRY_DETAIL>();
            this.TSPL_PP_SP_BATCH_ITEM_PRODUCTION_DETAIL = new HashSet<TSPL_PP_SP_BATCH_ITEM_PRODUCTION_DETAIL>();
            this.TSPL_PP_STD_FINALQC_BATCH_ITEM_DETAIL = new HashSet<TSPL_PP_STD_FINALQC_BATCH_ITEM_DETAIL>();
            this.TSPL_SPP_PRODUCTION_ENTRY = new HashSet<TSPL_SPP_PRODUCTION_ENTRY>();
            this.TSPL_SPP_PRODUCTION_ENTRY_DETAIL = new HashSet<TSPL_SPP_PRODUCTION_ENTRY_DETAIL>();
        }
    
        public string SHIFT_CODE { get; set; }
        public string SHIFT_NAME { get; set; }
        public Nullable<System.DateTime> FROM_Date { get; set; }
        public Nullable<System.DateTime> TO_Date { get; set; }
        public string Posted { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Modified_By { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public System.TimeSpan FROM_Time { get; set; }
        public System.TimeSpan TO_Time { get; set; }
        public System.TimeSpan INTERVAL_Time { get; set; }
        public Nullable<int> FSTHALF_ADJUST_MIN { get; set; }
        public Nullable<int> SECHALF_ADJUST_MIN { get; set; }
        public string comp_code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_EMPLOYEE_MASTER> TSPL_EMPLOYEE_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_EMPLOYEE_STATUS> TSPL_EMPLOYEE_STATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PRODUCTION_UPLOADER_DETAIL> TSPL_PRODUCTION_UPLOADER_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_EMPLOYEE_SHIFT_CHANGE_DETAIL> TSPL_EMPLOYEE_SHIFT_CHANGE_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PE_FINALQC_DETAIL> TSPL_PE_FINALQC_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PP_BATCH_ITEM_PRODUCTION_DETAIL> TSPL_PP_BATCH_ITEM_PRODUCTION_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PP_BATCH_ORDER_BOM_DETAIL> TSPL_PP_BATCH_ORDER_BOM_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PP_PRODUCTION_ENTRY_DETAIL> TSPL_PP_PRODUCTION_ENTRY_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PP_SP_BATCH_ITEM_PRODUCTION_DETAIL> TSPL_PP_SP_BATCH_ITEM_PRODUCTION_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PP_STD_FINALQC_BATCH_ITEM_DETAIL> TSPL_PP_STD_FINALQC_BATCH_ITEM_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_SPP_PRODUCTION_ENTRY> TSPL_SPP_PRODUCTION_ENTRY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_SPP_PRODUCTION_ENTRY_DETAIL> TSPL_SPP_PRODUCTION_ENTRY_DETAIL { get; set; }
    }
}
