//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_POS_GROUP_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSPL_POS_GROUP_MASTER()
        {
            this.TSPL_POS_COMMISSION_MAPPING = new HashSet<TSPL_POS_COMMISSION_MAPPING>();
        }
    
        public string GROUP_CODE { get; set; }
        public System.DateTime DOC_DATE { get; set; }
        public string DESCRIPTION { get; set; }
        public int LEVEL { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string CREATE_BY { get; set; }
        public System.DateTime MODIFY_DATE { get; set; }
        public string MODIFY_BY { get; set; }
    
        public virtual TSPL_USER_MASTER TSPL_USER_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_POS_COMMISSION_MAPPING> TSPL_POS_COMMISSION_MAPPING { get; set; }
        public virtual TSPL_USER_MASTER TSPL_USER_MASTER1 { get; set; }
    }
}
