//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tspl_Recurring_Scheduler_Head
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tspl_Recurring_Scheduler_Head()
        {
            this.TSPL_Mcc_Milk_Transport_Invoice_HEAD = new HashSet<TSPL_Mcc_Milk_Transport_Invoice_HEAD>();
            this.TSPL_Recurring_Payable_INVOICE_HEAD = new HashSet<TSPL_Recurring_Payable_INVOICE_HEAD>();
        }
    
        public string DOC_CODE { get; set; }
        public string Description { get; set; }
        public System.DateTime DOC_DATE { get; set; }
        public string User_Mode { get; set; }
        public string Recurring_period { get; set; }
        public int Duration { get; set; }
        public decimal Posted { get; set; }
        public Nullable<System.DateTime> Posting_Date { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Modified_By { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public string Comp_Code { get; set; }
        public int Remind_In_Advance { get; set; }
        public Nullable<System.DateTime> Sch_Start_Date { get; set; }
    
        public virtual TSPL_COMPANY_MASTER TSPL_COMPANY_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_Mcc_Milk_Transport_Invoice_HEAD> TSPL_Mcc_Milk_Transport_Invoice_HEAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_Recurring_Payable_INVOICE_HEAD> TSPL_Recurring_Payable_INVOICE_HEAD { get; set; }
        public virtual Tspl_Recurring_Scheduler_Detail Tspl_Recurring_Scheduler_Detail { get; set; }
        public virtual Tspl_Recurring_Scheduler_User_Detail Tspl_Recurring_Scheduler_User_Detail { get; set; }
    }
}
