//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tspl_Trainer_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tspl_Trainer_Master()
        {
            this.TSPL_HR_TRAINEE_FEEDBACK = new HashSet<TSPL_HR_TRAINEE_FEEDBACK>();
            this.TSPL_Schedule_Training_Head = new HashSet<TSPL_Schedule_Training_Head>();
        }
    
        public string DOC_Code { get; set; }
        public string DOC_Name { get; set; }
        public System.DateTime DOC_DATE { get; set; }
        public string Remark { get; set; }
        public string Type { get; set; }
        public string Institute_Code { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Employee_Code { get; set; }
        public string Payment_Type { get; set; }
        public string Add1 { get; set; }
        public string Add2 { get; set; }
        public string Add3 { get; set; }
        public string City_code { get; set; }
        public string State_Code { get; set; }
        public string Country_code { get; set; }
        public string Pin_code { get; set; }
        public string Telphone1 { get; set; }
        public string Telphone2 { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Is_Applicable { get; set; }
        public decimal Posted { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Modified_By { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public string Comp_Code { get; set; }
    
        public virtual TSPL_CITY_MASTER TSPL_CITY_MASTER { get; set; }
        public virtual TSPL_COMPANY_MASTER TSPL_COMPANY_MASTER { get; set; }
        public virtual TSPL_EMPLOYEE_MASTER TSPL_EMPLOYEE_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_HR_TRAINEE_FEEDBACK> TSPL_HR_TRAINEE_FEEDBACK { get; set; }
        public virtual Tspl_Institute_Master Tspl_Institute_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_Schedule_Training_Head> TSPL_Schedule_Training_Head { get; set; }
        public virtual TSPL_STATE_MASTER TSPL_STATE_MASTER { get; set; }
        public virtual Tspl_Trainer_Master_City Tspl_Trainer_Master_City { get; set; }
        public virtual Tspl_Trainer_Master_Course Tspl_Trainer_Master_Course { get; set; }
        public virtual Tspl_Trainer_Master_Qualification Tspl_Trainer_Master_Qualification { get; set; }
    }
}
