//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tspl_HR_EM_Exit_Interview_Detail
    {
        public string Exit_code { get; set; }
        public Nullable<int> Line_No { get; set; }
        public string Ques_Code { get; set; }
        public Nullable<int> Strongly_Agree { get; set; }
        public Nullable<int> SomeWhat_agree { get; set; }
        public Nullable<int> SomeWhat_Disgree { get; set; }
        public Nullable<int> Strongly_Disagree { get; set; }
    
        public virtual Tspl_HR_EM_Exit_Interview_Head Tspl_HR_EM_Exit_Interview_Head { get; set; }
        public virtual Tspl_HR_EM_Exit_Question Tspl_HR_EM_Exit_Question { get; set; }
    }
}
