//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_VSP_INCENTIVE_Detail
    {
        public string Doc_Code { get; set; }
        public string VSP_CODE { get; set; }
        public string INCENTIVE_CODE { get; set; }
        public string MCC_Code { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Modified_By { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public string comp_code { get; set; }
        public string StartDate { get; set; }
        public string StartShift { get; set; }
        public string EndDate { get; set; }
        public string EndShift { get; set; }
        public Nullable<bool> VSPSelect { get; set; }
    
        public virtual TSPL_INCENTIVE_MASTER_HEAD TSPL_INCENTIVE_MASTER_HEAD { get; set; }
        public virtual TSPL_MCC_MASTER TSPL_MCC_MASTER { get; set; }
        public virtual TSPL_VENDOR_MASTER TSPL_VENDOR_MASTER { get; set; }
    }
}
