//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_UNIT_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSPL_UNIT_MASTER()
        {
            this.TSPL_ANDROID_MCC_SALE_REQUEST = new HashSet<TSPL_ANDROID_MCC_SALE_REQUEST>();
            this.TSPL_ANDROID_MP_SALE = new HashSet<TSPL_ANDROID_MP_SALE>();
            this.TSPL_BATCH_ITEM = new HashSet<TSPL_BATCH_ITEM>();
            this.TSPL_BATCH_ITEM_INDIRECT = new HashSet<TSPL_BATCH_ITEM_INDIRECT>();
            this.TSPL_BATCH_ITEM_NEW = new HashSet<TSPL_BATCH_ITEM_NEW>();
            this.TSPL_BOM_HEAD_PP = new HashSet<TSPL_BOM_HEAD_PP>();
            this.TSPL_BulkSalePrice_MASTER = new HashSet<TSPL_BulkSalePrice_MASTER>();
            this.TSPL_CSA_PRICE_HEAD = new HashSet<TSPL_CSA_PRICE_HEAD>();
            this.TSPL_CUSTOMER_INCENTIVE_CUSTOMER_INCENTIVE_WISE = new HashSet<TSPL_CUSTOMER_INCENTIVE_CUSTOMER_INCENTIVE_WISE>();
            this.TSPL_CUSTOMER_INCENTIVE_CUSTOMER_INCENTIVE_WISE1 = new HashSet<TSPL_CUSTOMER_INCENTIVE_CUSTOMER_INCENTIVE_WISE>();
            this.TSPL_CUSTOMER_INCENTIVE_INVOICE_WISE = new HashSet<TSPL_CUSTOMER_INCENTIVE_INVOICE_WISE>();
            this.TSPL_CUSTOMER_INCENTIVE_ITEM_CUSTOMER_WISE = new HashSet<TSPL_CUSTOMER_INCENTIVE_ITEM_CUSTOMER_WISE>();
            this.TSPL_CUSTOMER_INCENTIVE_ITEM_CUSTOMER_WISE1 = new HashSet<TSPL_CUSTOMER_INCENTIVE_ITEM_CUSTOMER_WISE>();
            this.TSPL_CUSTOMER_INCENTIVE_ITEM_CUSTOMER_WISE2 = new HashSet<TSPL_CUSTOMER_INCENTIVE_ITEM_CUSTOMER_WISE>();
            this.TSPL_CUSTOMER_INCENTIVE_STRUCTURE_CUSTOMER_WISE = new HashSet<TSPL_CUSTOMER_INCENTIVE_STRUCTURE_CUSTOMER_WISE>();
            this.TSPL_CUSTOMER_INCENTIVE_STRUCTURE_CUSTOMER_WISE1 = new HashSet<TSPL_CUSTOMER_INCENTIVE_STRUCTURE_CUSTOMER_WISE>();
            this.TSPL_CUSTOMER_INCENTIVE_STRUCTURE_CUSTOMER_WISE2 = new HashSet<TSPL_CUSTOMER_INCENTIVE_STRUCTURE_CUSTOMER_WISE>();
            this.TSPL_DCS_FOR_SALE_FRIEGHT_DETAIL = new HashSet<TSPL_DCS_FOR_SALE_FRIEGHT_DETAIL>();
            this.TSPL_DISTRIBUTOR_COMMISSION_HEAD = new HashSet<TSPL_DISTRIBUTOR_COMMISSION_HEAD>();
            this.TSPL_JWI_ESTIMATION_FAT_PRODUCTION = new HashSet<TSPL_JWI_ESTIMATION_FAT_PRODUCTION>();
            this.TSPL_JWI_ESTIMATION_RAW_ITEM = new HashSet<TSPL_JWI_ESTIMATION_RAW_ITEM>();
            this.TSPL_JWI_ESTIMATION_RAW_ITEM1 = new HashSet<TSPL_JWI_ESTIMATION_RAW_ITEM>();
            this.TSPL_JWI_ESTIMATION_SNF_PRODUCTION = new HashSet<TSPL_JWI_ESTIMATION_SNF_PRODUCTION>();
            this.TSPL_JWI_ESTIMATION_WEIGHMENT = new HashSet<TSPL_JWI_ESTIMATION_WEIGHMENT>();
            this.TSPL_JWO_ESTIMATION_FAT_PRODUCTION = new HashSet<TSPL_JWO_ESTIMATION_FAT_PRODUCTION>();
            this.TSPL_JWO_ESTIMATION_RAW_ITEM = new HashSet<TSPL_JWO_ESTIMATION_RAW_ITEM>();
            this.TSPL_JWO_ESTIMATION_RAW_ITEM1 = new HashSet<TSPL_JWO_ESTIMATION_RAW_ITEM>();
            this.TSPL_JWO_ESTIMATION_SNF_PRODUCTION = new HashSet<TSPL_JWO_ESTIMATION_SNF_PRODUCTION>();
            this.TSPL_JWO_ESTIMATION_TRANSFER = new HashSet<TSPL_JWO_ESTIMATION_TRANSFER>();
            this.TSPL_MATERIAL_SALE_RATE_DETAIL = new HashSet<TSPL_MATERIAL_SALE_RATE_DETAIL>();
            this.TSPL_MCC_RATE_UPLOADER_Detail = new HashSet<TSPL_MCC_RATE_UPLOADER_Detail>();
            this.TSPL_MF_BOM_HEAD = new HashSet<TSPL_MF_BOM_HEAD>();
            this.TSPL_MF_CONSUMPTION_DETAIL = new HashSet<TSPL_MF_CONSUMPTION_DETAIL>();
            this.TSPL_MF_MANUFACTURING_ORDER = new HashSet<TSPL_MF_MANUFACTURING_ORDER>();
            this.TSPL_MF_MANUFACTURING_ORDER1 = new HashSet<TSPL_MF_MANUFACTURING_ORDER>();
            this.TSPL_MF_RESOURCE_MASTER = new HashSet<TSPL_MF_RESOURCE_MASTER>();
            this.TSPL_MF_TOOL_MASTER = new HashSet<TSPL_MF_TOOL_MASTER>();
            this.TSPL_MF_TOOL_TYPE = new HashSet<TSPL_MF_TOOL_TYPE>();
            this.TSPL_MRP_HEAD = new HashSet<TSPL_MRP_HEAD>();
            this.TSPL_PE_FINALQC_CONSUMPTION = new HashSet<TSPL_PE_FINALQC_CONSUMPTION>();
            this.TSPL_PJC_ASSEMBLIES = new HashSet<TSPL_PJC_ASSEMBLIES>();
            this.TSPL_PJC_TASK = new HashSet<TSPL_PJC_TASK>();
            this.TSPL_PP_BOM_HEAD = new HashSet<TSPL_PP_BOM_HEAD>();
            this.TSPL_PP_PRODUCTION_CONSUMPTION_DETAIL = new HashSet<TSPL_PP_PRODUCTION_CONSUMPTION_DETAIL>();
            this.TSPL_PROD_ASSEMBLIES = new HashSet<TSPL_PROD_ASSEMBLIES>();
            this.TSPL_RCDF_STD_ADD_REMOVE = new HashSet<TSPL_RCDF_STD_ADD_REMOVE>();
            this.TSPL_RCDF_STD_ISSUE = new HashSet<TSPL_RCDF_STD_ISSUE>();
            this.TSPL_RCDF_STD_PRODUCE = new HashSet<TSPL_RCDF_STD_PRODUCE>();
            this.TSPL_RICE_MIXING_HEAD = new HashSet<TSPL_RICE_MIXING_HEAD>();
            this.TSPL_SALES_INCENTIVE_HEADER = new HashSet<TSPL_SALES_INCENTIVE_HEADER>();
            this.TSPL_SALES_INCENTIVE_HEADER1 = new HashSet<TSPL_SALES_INCENTIVE_HEADER>();
            this.TSPL_SCHEME_MASTER_NEW = new HashSet<TSPL_SCHEME_MASTER_NEW>();
            this.TSPL_SCHEME_MASTER_NEW1 = new HashSet<TSPL_SCHEME_MASTER_NEW>();
            this.TSPL_SCHEME_MASTER_NEW2 = new HashSet<TSPL_SCHEME_MASTER_NEW>();
            this.TSPL_SCHEME_MASTER_NEW3 = new HashSet<TSPL_SCHEME_MASTER_NEW>();
            this.TSPL_SD_SHIPMENT_DCS_ITEM_DETAIL = new HashSet<TSPL_SD_SHIPMENT_DCS_ITEM_DETAIL>();
            this.TSPL_SET_PO_SCHEDULE_DETAIL = new HashSet<TSPL_SET_PO_SCHEDULE_DETAIL>();
            this.TSPL_SILO_MILK_TRANSFER_HEAD = new HashSet<TSPL_SILO_MILK_TRANSFER_HEAD>();
            this.TSPL_SPP_PRODUCTION_CONSUMPTION_DETAIL = new HashSet<TSPL_SPP_PRODUCTION_CONSUMPTION_DETAIL>();
            this.TSPL_ACKNOWLEDGENT_ENTRY_DETAIL = new HashSet<TSPL_ACKNOWLEDGENT_ENTRY_DETAIL>();
            this.TSPL_BOM_DETAIL_PP = new HashSet<TSPL_BOM_DETAIL_PP>();
            this.TSPL_BOOKING_DETAIL_PRODUCTSALE = new HashSet<TSPL_BOOKING_DETAIL_PRODUCTSALE>();
            this.TSPL_BulkSalePrice_MASTER_History = new HashSet<TSPL_BulkSalePrice_MASTER_History>();
            this.TSPL_CSA_BOOKING_DETAIL = new HashSet<TSPL_CSA_BOOKING_DETAIL>();
            this.TSPL_CSA_BOOKING_DETAIL1 = new HashSet<TSPL_CSA_BOOKING_DETAIL>();
            this.TSPL_CSA_PRICE_DETAIL = new HashSet<TSPL_CSA_PRICE_DETAIL>();
            this.TSPL_CSA_DO_DETAIL = new HashSet<TSPL_CSA_DO_DETAIL>();
            this.TSPL_CSA_PRICE_DETAIL1 = new HashSet<TSPL_CSA_PRICE_DETAIL>();
            this.TSPL_CSA_PRICE_OTHER_ITEM_DETAIL = new HashSet<TSPL_CSA_PRICE_OTHER_ITEM_DETAIL>();
            this.TSPL_DAIRY_PROFORMA_INVOICE_DETAIL = new HashSet<TSPL_DAIRY_PROFORMA_INVOICE_DETAIL>();
            this.TSPL_DAIRY_PROFORMA_INVOICE_DETAIL1 = new HashSet<TSPL_DAIRY_PROFORMA_INVOICE_DETAIL>();
            this.TSPL_DELIVERY_ORDER_DETAIL_PRODUCTSALE = new HashSet<TSPL_DELIVERY_ORDER_DETAIL_PRODUCTSALE>();
            this.TSPL_DELIVERY_ORDER_DETAIL_PRODUCTSALE1 = new HashSet<TSPL_DELIVERY_ORDER_DETAIL_PRODUCTSALE>();
            this.TSPL_DELIVERY_ORDER_DETAIL_PRODUCTSALE2 = new HashSet<TSPL_DELIVERY_ORDER_DETAIL_PRODUCTSALE>();
            this.TSPL_DELIVERY_ORDER_DETAIL_PRODUCTSALE3 = new HashSet<TSPL_DELIVERY_ORDER_DETAIL_PRODUCTSALE>();
            this.TSPL_DISPATCH_ADVICE_DETAIL_PRODUCTSALE = new HashSet<TSPL_DISPATCH_ADVICE_DETAIL_PRODUCTSALE>();
            this.TSPL_DISPATCH_ADVICE_DETAIL_PRODUCTSALE1 = new HashSet<TSPL_DISPATCH_ADVICE_DETAIL_PRODUCTSALE>();
            this.TSPL_DISPATCH_ADVICE_DETAIL_PRODUCTSALE2 = new HashSet<TSPL_DISPATCH_ADVICE_DETAIL_PRODUCTSALE>();
            this.TSPL_DISPATCH_ADVICE_DETAIL_PRODUCTSALE3 = new HashSet<TSPL_DISPATCH_ADVICE_DETAIL_PRODUCTSALE>();
            this.TSPL_GRN_RGP_CONVERSION_DETAIL = new HashSet<TSPL_GRN_RGP_CONVERSION_DETAIL>();
            this.TSPL_ITEM_COMMISSION_FREIGHT_AC_DETAIL = new HashSet<TSPL_ITEM_COMMISSION_FREIGHT_AC_DETAIL>();
            this.TSPL_ITEM_COMMISSION_FREIGHT_AC_DETAIL1 = new HashSet<TSPL_ITEM_COMMISSION_FREIGHT_AC_DETAIL>();
            this.TSPL_ITEM_REORDER_LEVEL_NEW = new HashSet<TSPL_ITEM_REORDER_LEVEL_NEW>();
            this.TSPL_JWI_PRICE_DETAIL = new HashSet<TSPL_JWI_PRICE_DETAIL>();
            this.TSPL_JWI_PRICE_DETAIL_ALL_UOM = new HashSet<TSPL_JWI_PRICE_DETAIL_ALL_UOM>();
            this.TSPL_JWO_SRN_DETAIL = new HashSet<TSPL_JWO_SRN_DETAIL>();
            this.TSPL_MCC_SALE_FARMER_DETAIL = new HashSet<TSPL_MCC_SALE_FARMER_DETAIL>();
            this.TSPL_MCC_SALE_RETURN_DETAIL_FARMER = new HashSet<TSPL_MCC_SALE_RETURN_DETAIL_FARMER>();
            this.TSPL_MCC_SALE_FARMER_DETAIL1 = new HashSet<TSPL_MCC_SALE_FARMER_DETAIL>();
            this.TSPL_MCC_SALE_FARMER_DETAIL2 = new HashSet<TSPL_MCC_SALE_FARMER_DETAIL>();
            this.TSPL_MCC_TANKER_DISPATCH_RETURN_DETAIL = new HashSet<TSPL_MCC_TANKER_DISPATCH_RETURN_DETAIL>();
            this.TSPL_MCC_DISPATCH_CHALLAN_DETAIL = new HashSet<TSPL_MCC_DISPATCH_CHALLAN_DETAIL>();
            this.TSPL_MCC_SALE_FARMER_DETAIL3 = new HashSet<TSPL_MCC_SALE_FARMER_DETAIL>();
            this.TSPL_MCC_SALE_RETURN_DETAIL_FARMER1 = new HashSet<TSPL_MCC_SALE_RETURN_DETAIL_FARMER>();
            this.TSPL_MF_BOM_DETAIL = new HashSet<TSPL_MF_BOM_DETAIL>();
            this.TSPL_MF_BATCH_ORDER_DETAIL = new HashSet<TSPL_MF_BATCH_ORDER_DETAIL>();
            this.TSPL_MF_BATCH_PP_DETAIL = new HashSet<TSPL_MF_BATCH_PP_DETAIL>();
            this.TSPL_MF_ISSUE_DETAIL = new HashSet<TSPL_MF_ISSUE_DETAIL>();
            this.TSPL_MF_MO_MATERIAL = new HashSet<TSPL_MF_MO_MATERIAL>();
            this.TSPL_MF_PROD_PLAN_DETAIL = new HashSet<TSPL_MF_PROD_PLAN_DETAIL>();
            this.TSPL_MF_RECEIPT_DETAIL = new HashSet<TSPL_MF_RECEIPT_DETAIL>();
            this.TSPL_MF_REQ_DETAIL = new HashSet<TSPL_MF_REQ_DETAIL>();
            this.TSPL_MF_RETURN_DETAIL = new HashSet<TSPL_MF_RETURN_DETAIL>();
            this.TSPL_MF_SUBSTITUTE_ITEMS = new HashSet<TSPL_MF_SUBSTITUTE_ITEMS>();
            this.TSPL_MILK_PURCHASE_INVOICE_MP_COLLEC_SUMMARY = new HashSet<TSPL_MILK_PURCHASE_INVOICE_MP_COLLEC_SUMMARY>();
            this.TSPL_MILK_PURCHASE_INVOICE_MP_DETAIL = new HashSet<TSPL_MILK_PURCHASE_INVOICE_MP_DETAIL>();
            this.TSPL_MRP_DETAIL = new HashSet<TSPL_MRP_DETAIL>();
            this.TSPL_MRP_PO_DETAIL = new HashSet<TSPL_MRP_PO_DETAIL>();
            this.TSPL_NRGP_REQUEST_DETAIL = new HashSet<TSPL_NRGP_REQUEST_DETAIL>();
            this.TSPL_NRGP_REQUEST_DETAIL1 = new HashSet<TSPL_NRGP_REQUEST_DETAIL>();
            this.TSPL_PE_FINALQC_STAGE_DETAIL = new HashSet<TSPL_PE_FINALQC_STAGE_DETAIL>();
            this.TSPL_PE_FINALQC_WRECKAGE_FLUSHING_ITEM = new HashSet<TSPL_PE_FINALQC_WRECKAGE_FLUSHING_ITEM>();
            this.TSPL_PE_FINALQC_SCRAP_ITEM = new HashSet<TSPL_PE_FINALQC_SCRAP_ITEM>();
            this.TSPL_PE_FINALQC_DETAIL = new HashSet<TSPL_PE_FINALQC_DETAIL>();
            this.TSPL_PE_FINALQC_ISSUE_ITEM = new HashSet<TSPL_PE_FINALQC_ISSUE_ITEM>();
            this.TSPL_PHYSICAL_STOCK = new HashSet<TSPL_PHYSICAL_STOCK>();
            this.TSPL_PJC_ASSEMBLIES_ITEM_DETAIL = new HashSet<TSPL_PJC_ASSEMBLIES_ITEM_DETAIL>();
            this.TSPL_PO_SCH_DETAIL = new HashSet<TSPL_PO_SCH_DETAIL>();
            this.TSPL_PO_VENDOR_SCH_DETAIL = new HashSet<TSPL_PO_VENDOR_SCH_DETAIL>();
            this.TSPL_POS_BOOKING_DETAIL = new HashSet<TSPL_POS_BOOKING_DETAIL>();
            this.TSPL_PP_BATCH_ORDER_RAW_ITEM_DETAIL = new HashSet<TSPL_PP_BATCH_ORDER_RAW_ITEM_DETAIL>();
            this.TSPL_PP_BOM_ITEM_DETAIL = new HashSet<TSPL_PP_BOM_ITEM_DETAIL>();
            this.TSPL_PP_BATCH_ITEM_PRODUCTION_DETAIL = new HashSet<TSPL_PP_BATCH_ITEM_PRODUCTION_DETAIL>();
            this.TSPL_PP_BATCH_ORDER_BOM_DETAIL = new HashSet<TSPL_PP_BATCH_ORDER_BOM_DETAIL>();
            this.TSPL_PP_CONSUMPTION_WITHOUT_BATCH = new HashSet<TSPL_PP_CONSUMPTION_WITHOUT_BATCH>();
            this.TSPL_PP_COST_WITHOUT_BATCH = new HashSet<TSPL_PP_COST_WITHOUT_BATCH>();
            this.TSPL_PP_CONSUMPTION_WITHOUT_BATCH1 = new HashSet<TSPL_PP_CONSUMPTION_WITHOUT_BATCH>();
            this.TSPL_PP_ISSUE_ITEM_DETAIL = new HashSet<TSPL_PP_ISSUE_ITEM_DETAIL>();
            this.TSPL_PP_PE_ISSUE_ITEM_DETAIL = new HashSet<TSPL_PP_PE_ISSUE_ITEM_DETAIL>();
            this.TSPL_PP_PE_SCRAP_DETAIL = new HashSet<TSPL_PP_PE_SCRAP_DETAIL>();
            this.TSPL_PP_PE_STAGE_DETAIL = new HashSet<TSPL_PP_PE_STAGE_DETAIL>();
            this.TSPL_PP_PE_WRECKAGE_FLASHING = new HashSet<TSPL_PP_PE_WRECKAGE_FLASHING>();
            this.TSPL_PP_PRODUCTION_ENTRY_DETAIL = new HashSet<TSPL_PP_PRODUCTION_ENTRY_DETAIL>();
            this.TSPL_PP_PRODUCTION_PLAN_DETAIL = new HashSet<TSPL_PP_PRODUCTION_PLAN_DETAIL>();
            this.TSPL_PP_STD_FINALQC_ISSUE_ITEM_DETAIL = new HashSet<TSPL_PP_STD_FINALQC_ISSUE_ITEM_DETAIL>();
            this.TSPL_PP_STD_FINALQC_ADD_REMOVE_ITEM_DETAIL = new HashSet<TSPL_PP_STD_FINALQC_ADD_REMOVE_ITEM_DETAIL>();
            this.TSPL_PP_STD_ADD_REMOVE_ITEM_DETAIL = new HashSet<TSPL_PP_STD_ADD_REMOVE_ITEM_DETAIL>();
            this.TSPL_PP_STD_ISSUE_ITEM_DETAIL = new HashSet<TSPL_PP_STD_ISSUE_ITEM_DETAIL>();
            this.TSPL_PP_STD_FINALQC_STAGE_DETAIL = new HashSet<TSPL_PP_STD_FINALQC_STAGE_DETAIL>();
            this.TSPL_PP_STD_STAGE_DETAIL = new HashSet<TSPL_PP_STD_STAGE_DETAIL>();
            this.TSPL_PP_SP_ADD_REMOVE_ITEM_DETAIL = new HashSet<TSPL_PP_SP_ADD_REMOVE_ITEM_DETAIL>();
            this.TSPL_PP_SP_BATCH_ITEM_PRODUCTION_DETAIL = new HashSet<TSPL_PP_SP_BATCH_ITEM_PRODUCTION_DETAIL>();
            this.TSPL_PP_STD_FINALQC_BATCH_ITEM_DETAIL = new HashSet<TSPL_PP_STD_FINALQC_BATCH_ITEM_DETAIL>();
            this.TSPL_PP_SP_ISSUE_ITEM_DETAIL = new HashSet<TSPL_PP_SP_ISSUE_ITEM_DETAIL>();
            this.TSPL_PP_STAGE_PROCESS_DETAIL = new HashSet<TSPL_PP_STAGE_PROCESS_DETAIL>();
            this.TSPL_PROD_ASSEMBLIES_ITEM_DETAIL = new HashSet<TSPL_PROD_ASSEMBLIES_ITEM_DETAIL>();
            this.TSPL_QC_CHECK_DETAIL = new HashSet<TSPL_QC_CHECK_DETAIL>();
            this.TSPL_QC_CHECK_MRN_DETAIL = new HashSet<TSPL_QC_CHECK_MRN_DETAIL>();
            this.TSPL_QC_CHECK_SRN_DETAIL = new HashSet<TSPL_QC_CHECK_SRN_DETAIL>();
            this.TSPL_QC_VENDOR_ITEM_MAPPING_DETAIL = new HashSet<TSPL_QC_VENDOR_ITEM_MAPPING_DETAIL>();
            this.TSPL_RGP_JOB_WORK_DETAIL = new HashSet<TSPL_RGP_JOB_WORK_DETAIL>();
            this.TSPL_RICE_MIXING_DETAIL = new HashSet<TSPL_RICE_MIXING_DETAIL>();
            this.TSPL_RICE_MIXING_FINISH_DETAIL = new HashSet<TSPL_RICE_MIXING_FINISH_DETAIL>();
            this.TSPL_RICE_PROCESSING_DETAIL = new HashSet<TSPL_RICE_PROCESSING_DETAIL>();
            this.TSPL_RICE_PROCESSING_FINISH_DETAIL = new HashSet<TSPL_RICE_PROCESSING_FINISH_DETAIL>();
            this.TSPL_SALE_RETURN_GATE_ENTRY_DETAIL = new HashSet<TSPL_SALE_RETURN_GATE_ENTRY_DETAIL>();
            this.TSPL_SD_SALE_INVOICE_DETAIL = new HashSet<TSPL_SD_SALE_INVOICE_DETAIL>();
            this.TSPL_SD_SALE_RETURN_DETAIL = new HashSet<TSPL_SD_SALE_RETURN_DETAIL>();
            this.TSPL_SD_SALES_ORDER_DETAIL = new HashSet<TSPL_SD_SALES_ORDER_DETAIL>();
            this.TSPL_SD_SHIPMENT_DETAIL = new HashSet<TSPL_SD_SHIPMENT_DETAIL>();
            this.TSPL_SD_SALE_INVOICE_DETAIL1 = new HashSet<TSPL_SD_SALE_INVOICE_DETAIL>();
            this.TSPL_SD_SALE_INVOICE_DETAIL2 = new HashSet<TSPL_SD_SALE_INVOICE_DETAIL>();
            this.TSPL_SD_SALES_ORDER_DETAIL1 = new HashSet<TSPL_SD_SALES_ORDER_DETAIL>();
            this.TSPL_SD_SALES_ORDER_DETAIL2 = new HashSet<TSPL_SD_SALES_ORDER_DETAIL>();
            this.TSPL_SD_SHIPMENT_DETAIL1 = new HashSet<TSPL_SD_SHIPMENT_DETAIL>();
            this.TSPL_SD_SHIPMENT_DETAIL2 = new HashSet<TSPL_SD_SHIPMENT_DETAIL>();
            this.TSPL_SD_SHIPMENT_DETAIL3 = new HashSet<TSPL_SD_SHIPMENT_DETAIL>();
            this.TSPL_SD_SALE_INVOICE_DETAIL3 = new HashSet<TSPL_SD_SALE_INVOICE_DETAIL>();
            this.TSPL_SD_SALE_RETURN_DETAIL1 = new HashSet<TSPL_SD_SALE_RETURN_DETAIL>();
            this.TSPL_SD_SALES_ORDER_DETAIL3 = new HashSet<TSPL_SD_SALES_ORDER_DETAIL>();
            this.TSPL_SILO_MILK_TRANSFER_DETAIL = new HashSet<TSPL_SILO_MILK_TRANSFER_DETAIL>();
            this.TSPL_SPP_COST_WITHOUT_BATCH = new HashSet<TSPL_SPP_COST_WITHOUT_BATCH>();
            this.TSPL_SPP_CONSUMPTION_WITHOUT_BATCH = new HashSet<TSPL_SPP_CONSUMPTION_WITHOUT_BATCH>();
            this.TSPL_SPP_PE_WRECKAGE_FLASHING = new HashSet<TSPL_SPP_PE_WRECKAGE_FLASHING>();
            this.TSPL_SPP_PE_STAGE_DETAIL = new HashSet<TSPL_SPP_PE_STAGE_DETAIL>();
            this.TSPL_SPP_PE_ISSUE_ITEM_DETAIL = new HashSet<TSPL_SPP_PE_ISSUE_ITEM_DETAIL>();
            this.TSPL_SPP_CONSUMPTION_WITHOUT_BATCH1 = new HashSet<TSPL_SPP_CONSUMPTION_WITHOUT_BATCH>();
            this.TSPL_SPP_PRODUCTION_ENTRY_DETAIL = new HashSet<TSPL_SPP_PRODUCTION_ENTRY_DETAIL>();
            this.TSPL_SPP_PE_SCRAP_DETAIL = new HashSet<TSPL_SPP_PE_SCRAP_DETAIL>();
            this.TSPL_TANKER_MASTER_SALE_DETAIL = new HashSet<TSPL_TANKER_MASTER_SALE_DETAIL>();
            this.TSPL_VLC_MASTER_HEAD = new HashSet<TSPL_VLC_MASTER_HEAD>();
            this.TSPL_WRECKAGE_BOOKING = new HashSet<TSPL_WRECKAGE_BOOKING>();
        }
    
        public string Unit_Code { get; set; }
        public string Unit_Desc { get; set; }
        public Nullable<decimal> Conv_Factor { get; set; }
        public string Created_By { get; set; }
        public string Created_Date { get; set; }
        public string Modify_By { get; set; }
        public string Modify_Date { get; set; }
        public string Comp_Code { get; set; }
        public string Empty { get; set; }
        public string Create_Price { get; set; }
        public string Weight_Type { get; set; }
        public string Crate_Type { get; set; }
        public string RT_Rate { get; set; }
        public string Ltr_Type { get; set; }
        public string Box_Type { get; set; }
        public string Can_Type { get; set; }
        public string Item_Category { get; set; }
        public string Packet_Type { get; set; }
        public string GST_UNIT_CODE { get; set; }
        public string Unit_Desc_Hindi { get; set; }
        public bool IsDefault { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_ANDROID_MCC_SALE_REQUEST> TSPL_ANDROID_MCC_SALE_REQUEST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_ANDROID_MP_SALE> TSPL_ANDROID_MP_SALE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_BATCH_ITEM> TSPL_BATCH_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_BATCH_ITEM_INDIRECT> TSPL_BATCH_ITEM_INDIRECT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_BATCH_ITEM_NEW> TSPL_BATCH_ITEM_NEW { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_BOM_HEAD_PP> TSPL_BOM_HEAD_PP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_BulkSalePrice_MASTER> TSPL_BulkSalePrice_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_CSA_PRICE_HEAD> TSPL_CSA_PRICE_HEAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_CUSTOMER_INCENTIVE_CUSTOMER_INCENTIVE_WISE> TSPL_CUSTOMER_INCENTIVE_CUSTOMER_INCENTIVE_WISE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_CUSTOMER_INCENTIVE_CUSTOMER_INCENTIVE_WISE> TSPL_CUSTOMER_INCENTIVE_CUSTOMER_INCENTIVE_WISE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_CUSTOMER_INCENTIVE_INVOICE_WISE> TSPL_CUSTOMER_INCENTIVE_INVOICE_WISE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_CUSTOMER_INCENTIVE_ITEM_CUSTOMER_WISE> TSPL_CUSTOMER_INCENTIVE_ITEM_CUSTOMER_WISE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_CUSTOMER_INCENTIVE_ITEM_CUSTOMER_WISE> TSPL_CUSTOMER_INCENTIVE_ITEM_CUSTOMER_WISE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_CUSTOMER_INCENTIVE_ITEM_CUSTOMER_WISE> TSPL_CUSTOMER_INCENTIVE_ITEM_CUSTOMER_WISE2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_CUSTOMER_INCENTIVE_STRUCTURE_CUSTOMER_WISE> TSPL_CUSTOMER_INCENTIVE_STRUCTURE_CUSTOMER_WISE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_CUSTOMER_INCENTIVE_STRUCTURE_CUSTOMER_WISE> TSPL_CUSTOMER_INCENTIVE_STRUCTURE_CUSTOMER_WISE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_CUSTOMER_INCENTIVE_STRUCTURE_CUSTOMER_WISE> TSPL_CUSTOMER_INCENTIVE_STRUCTURE_CUSTOMER_WISE2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_DCS_FOR_SALE_FRIEGHT_DETAIL> TSPL_DCS_FOR_SALE_FRIEGHT_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_DISTRIBUTOR_COMMISSION_HEAD> TSPL_DISTRIBUTOR_COMMISSION_HEAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_JWI_ESTIMATION_FAT_PRODUCTION> TSPL_JWI_ESTIMATION_FAT_PRODUCTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_JWI_ESTIMATION_RAW_ITEM> TSPL_JWI_ESTIMATION_RAW_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_JWI_ESTIMATION_RAW_ITEM> TSPL_JWI_ESTIMATION_RAW_ITEM1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_JWI_ESTIMATION_SNF_PRODUCTION> TSPL_JWI_ESTIMATION_SNF_PRODUCTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_JWI_ESTIMATION_WEIGHMENT> TSPL_JWI_ESTIMATION_WEIGHMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_JWO_ESTIMATION_FAT_PRODUCTION> TSPL_JWO_ESTIMATION_FAT_PRODUCTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_JWO_ESTIMATION_RAW_ITEM> TSPL_JWO_ESTIMATION_RAW_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_JWO_ESTIMATION_RAW_ITEM> TSPL_JWO_ESTIMATION_RAW_ITEM1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_JWO_ESTIMATION_SNF_PRODUCTION> TSPL_JWO_ESTIMATION_SNF_PRODUCTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_JWO_ESTIMATION_TRANSFER> TSPL_JWO_ESTIMATION_TRANSFER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MATERIAL_SALE_RATE_DETAIL> TSPL_MATERIAL_SALE_RATE_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MCC_RATE_UPLOADER_Detail> TSPL_MCC_RATE_UPLOADER_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MF_BOM_HEAD> TSPL_MF_BOM_HEAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MF_CONSUMPTION_DETAIL> TSPL_MF_CONSUMPTION_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MF_MANUFACTURING_ORDER> TSPL_MF_MANUFACTURING_ORDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MF_MANUFACTURING_ORDER> TSPL_MF_MANUFACTURING_ORDER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MF_RESOURCE_MASTER> TSPL_MF_RESOURCE_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MF_TOOL_MASTER> TSPL_MF_TOOL_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MF_TOOL_TYPE> TSPL_MF_TOOL_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MRP_HEAD> TSPL_MRP_HEAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PE_FINALQC_CONSUMPTION> TSPL_PE_FINALQC_CONSUMPTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PJC_ASSEMBLIES> TSPL_PJC_ASSEMBLIES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PJC_TASK> TSPL_PJC_TASK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PP_BOM_HEAD> TSPL_PP_BOM_HEAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PP_PRODUCTION_CONSUMPTION_DETAIL> TSPL_PP_PRODUCTION_CONSUMPTION_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PROD_ASSEMBLIES> TSPL_PROD_ASSEMBLIES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_RCDF_STD_ADD_REMOVE> TSPL_RCDF_STD_ADD_REMOVE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_RCDF_STD_ISSUE> TSPL_RCDF_STD_ISSUE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_RCDF_STD_PRODUCE> TSPL_RCDF_STD_PRODUCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_RICE_MIXING_HEAD> TSPL_RICE_MIXING_HEAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_SALES_INCENTIVE_HEADER> TSPL_SALES_INCENTIVE_HEADER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_SALES_INCENTIVE_HEADER> TSPL_SALES_INCENTIVE_HEADER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_SCHEME_MASTER_NEW> TSPL_SCHEME_MASTER_NEW { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_SCHEME_MASTER_NEW> TSPL_SCHEME_MASTER_NEW1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_SCHEME_MASTER_NEW> TSPL_SCHEME_MASTER_NEW2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_SCHEME_MASTER_NEW> TSPL_SCHEME_MASTER_NEW3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_SD_SHIPMENT_DCS_ITEM_DETAIL> TSPL_SD_SHIPMENT_DCS_ITEM_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_SET_PO_SCHEDULE_DETAIL> TSPL_SET_PO_SCHEDULE_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_SILO_MILK_TRANSFER_HEAD> TSPL_SILO_MILK_TRANSFER_HEAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_SPP_PRODUCTION_CONSUMPTION_DETAIL> TSPL_SPP_PRODUCTION_CONSUMPTION_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_ACKNOWLEDGENT_ENTRY_DETAIL> TSPL_ACKNOWLEDGENT_ENTRY_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_BOM_DETAIL_PP> TSPL_BOM_DETAIL_PP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_BOOKING_DETAIL_PRODUCTSALE> TSPL_BOOKING_DETAIL_PRODUCTSALE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_BulkSalePrice_MASTER_History> TSPL_BulkSalePrice_MASTER_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_CSA_BOOKING_DETAIL> TSPL_CSA_BOOKING_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_CSA_BOOKING_DETAIL> TSPL_CSA_BOOKING_DETAIL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_CSA_PRICE_DETAIL> TSPL_CSA_PRICE_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_CSA_DO_DETAIL> TSPL_CSA_DO_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_CSA_PRICE_DETAIL> TSPL_CSA_PRICE_DETAIL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_CSA_PRICE_OTHER_ITEM_DETAIL> TSPL_CSA_PRICE_OTHER_ITEM_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_DAIRY_PROFORMA_INVOICE_DETAIL> TSPL_DAIRY_PROFORMA_INVOICE_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_DAIRY_PROFORMA_INVOICE_DETAIL> TSPL_DAIRY_PROFORMA_INVOICE_DETAIL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_DELIVERY_ORDER_DETAIL_PRODUCTSALE> TSPL_DELIVERY_ORDER_DETAIL_PRODUCTSALE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_DELIVERY_ORDER_DETAIL_PRODUCTSALE> TSPL_DELIVERY_ORDER_DETAIL_PRODUCTSALE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_DELIVERY_ORDER_DETAIL_PRODUCTSALE> TSPL_DELIVERY_ORDER_DETAIL_PRODUCTSALE2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_DELIVERY_ORDER_DETAIL_PRODUCTSALE> TSPL_DELIVERY_ORDER_DETAIL_PRODUCTSALE3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_DISPATCH_ADVICE_DETAIL_PRODUCTSALE> TSPL_DISPATCH_ADVICE_DETAIL_PRODUCTSALE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_DISPATCH_ADVICE_DETAIL_PRODUCTSALE> TSPL_DISPATCH_ADVICE_DETAIL_PRODUCTSALE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_DISPATCH_ADVICE_DETAIL_PRODUCTSALE> TSPL_DISPATCH_ADVICE_DETAIL_PRODUCTSALE2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_DISPATCH_ADVICE_DETAIL_PRODUCTSALE> TSPL_DISPATCH_ADVICE_DETAIL_PRODUCTSALE3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_GRN_RGP_CONVERSION_DETAIL> TSPL_GRN_RGP_CONVERSION_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_ITEM_COMMISSION_FREIGHT_AC_DETAIL> TSPL_ITEM_COMMISSION_FREIGHT_AC_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_ITEM_COMMISSION_FREIGHT_AC_DETAIL> TSPL_ITEM_COMMISSION_FREIGHT_AC_DETAIL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_ITEM_REORDER_LEVEL_NEW> TSPL_ITEM_REORDER_LEVEL_NEW { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_JWI_PRICE_DETAIL> TSPL_JWI_PRICE_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_JWI_PRICE_DETAIL_ALL_UOM> TSPL_JWI_PRICE_DETAIL_ALL_UOM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_JWO_SRN_DETAIL> TSPL_JWO_SRN_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MCC_SALE_FARMER_DETAIL> TSPL_MCC_SALE_FARMER_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MCC_SALE_RETURN_DETAIL_FARMER> TSPL_MCC_SALE_RETURN_DETAIL_FARMER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MCC_SALE_FARMER_DETAIL> TSPL_MCC_SALE_FARMER_DETAIL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MCC_SALE_FARMER_DETAIL> TSPL_MCC_SALE_FARMER_DETAIL2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MCC_TANKER_DISPATCH_RETURN_DETAIL> TSPL_MCC_TANKER_DISPATCH_RETURN_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MCC_DISPATCH_CHALLAN_DETAIL> TSPL_MCC_DISPATCH_CHALLAN_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MCC_SALE_FARMER_DETAIL> TSPL_MCC_SALE_FARMER_DETAIL3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MCC_SALE_RETURN_DETAIL_FARMER> TSPL_MCC_SALE_RETURN_DETAIL_FARMER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MF_BOM_DETAIL> TSPL_MF_BOM_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MF_BATCH_ORDER_DETAIL> TSPL_MF_BATCH_ORDER_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MF_BATCH_PP_DETAIL> TSPL_MF_BATCH_PP_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MF_ISSUE_DETAIL> TSPL_MF_ISSUE_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MF_MO_MATERIAL> TSPL_MF_MO_MATERIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MF_PROD_PLAN_DETAIL> TSPL_MF_PROD_PLAN_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MF_RECEIPT_DETAIL> TSPL_MF_RECEIPT_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MF_REQ_DETAIL> TSPL_MF_REQ_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MF_RETURN_DETAIL> TSPL_MF_RETURN_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MF_SUBSTITUTE_ITEMS> TSPL_MF_SUBSTITUTE_ITEMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MILK_PURCHASE_INVOICE_MP_COLLEC_SUMMARY> TSPL_MILK_PURCHASE_INVOICE_MP_COLLEC_SUMMARY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MILK_PURCHASE_INVOICE_MP_DETAIL> TSPL_MILK_PURCHASE_INVOICE_MP_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MRP_DETAIL> TSPL_MRP_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MRP_PO_DETAIL> TSPL_MRP_PO_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_NRGP_REQUEST_DETAIL> TSPL_NRGP_REQUEST_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_NRGP_REQUEST_DETAIL> TSPL_NRGP_REQUEST_DETAIL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PE_FINALQC_STAGE_DETAIL> TSPL_PE_FINALQC_STAGE_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PE_FINALQC_WRECKAGE_FLUSHING_ITEM> TSPL_PE_FINALQC_WRECKAGE_FLUSHING_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PE_FINALQC_SCRAP_ITEM> TSPL_PE_FINALQC_SCRAP_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PE_FINALQC_DETAIL> TSPL_PE_FINALQC_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PE_FINALQC_ISSUE_ITEM> TSPL_PE_FINALQC_ISSUE_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PHYSICAL_STOCK> TSPL_PHYSICAL_STOCK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PJC_ASSEMBLIES_ITEM_DETAIL> TSPL_PJC_ASSEMBLIES_ITEM_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PO_SCH_DETAIL> TSPL_PO_SCH_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PO_VENDOR_SCH_DETAIL> TSPL_PO_VENDOR_SCH_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_POS_BOOKING_DETAIL> TSPL_POS_BOOKING_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PP_BATCH_ORDER_RAW_ITEM_DETAIL> TSPL_PP_BATCH_ORDER_RAW_ITEM_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PP_BOM_ITEM_DETAIL> TSPL_PP_BOM_ITEM_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PP_BATCH_ITEM_PRODUCTION_DETAIL> TSPL_PP_BATCH_ITEM_PRODUCTION_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PP_BATCH_ORDER_BOM_DETAIL> TSPL_PP_BATCH_ORDER_BOM_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PP_CONSUMPTION_WITHOUT_BATCH> TSPL_PP_CONSUMPTION_WITHOUT_BATCH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PP_COST_WITHOUT_BATCH> TSPL_PP_COST_WITHOUT_BATCH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PP_CONSUMPTION_WITHOUT_BATCH> TSPL_PP_CONSUMPTION_WITHOUT_BATCH1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PP_ISSUE_ITEM_DETAIL> TSPL_PP_ISSUE_ITEM_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PP_PE_ISSUE_ITEM_DETAIL> TSPL_PP_PE_ISSUE_ITEM_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PP_PE_SCRAP_DETAIL> TSPL_PP_PE_SCRAP_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PP_PE_STAGE_DETAIL> TSPL_PP_PE_STAGE_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PP_PE_WRECKAGE_FLASHING> TSPL_PP_PE_WRECKAGE_FLASHING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PP_PRODUCTION_ENTRY_DETAIL> TSPL_PP_PRODUCTION_ENTRY_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PP_PRODUCTION_PLAN_DETAIL> TSPL_PP_PRODUCTION_PLAN_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PP_STD_FINALQC_ISSUE_ITEM_DETAIL> TSPL_PP_STD_FINALQC_ISSUE_ITEM_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PP_STD_FINALQC_ADD_REMOVE_ITEM_DETAIL> TSPL_PP_STD_FINALQC_ADD_REMOVE_ITEM_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PP_STD_ADD_REMOVE_ITEM_DETAIL> TSPL_PP_STD_ADD_REMOVE_ITEM_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PP_STD_ISSUE_ITEM_DETAIL> TSPL_PP_STD_ISSUE_ITEM_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PP_STD_FINALQC_STAGE_DETAIL> TSPL_PP_STD_FINALQC_STAGE_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PP_STD_STAGE_DETAIL> TSPL_PP_STD_STAGE_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PP_SP_ADD_REMOVE_ITEM_DETAIL> TSPL_PP_SP_ADD_REMOVE_ITEM_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PP_SP_BATCH_ITEM_PRODUCTION_DETAIL> TSPL_PP_SP_BATCH_ITEM_PRODUCTION_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PP_STD_FINALQC_BATCH_ITEM_DETAIL> TSPL_PP_STD_FINALQC_BATCH_ITEM_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PP_SP_ISSUE_ITEM_DETAIL> TSPL_PP_SP_ISSUE_ITEM_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PP_STAGE_PROCESS_DETAIL> TSPL_PP_STAGE_PROCESS_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PROD_ASSEMBLIES_ITEM_DETAIL> TSPL_PROD_ASSEMBLIES_ITEM_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_QC_CHECK_DETAIL> TSPL_QC_CHECK_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_QC_CHECK_MRN_DETAIL> TSPL_QC_CHECK_MRN_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_QC_CHECK_SRN_DETAIL> TSPL_QC_CHECK_SRN_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_QC_VENDOR_ITEM_MAPPING_DETAIL> TSPL_QC_VENDOR_ITEM_MAPPING_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_RGP_JOB_WORK_DETAIL> TSPL_RGP_JOB_WORK_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_RICE_MIXING_DETAIL> TSPL_RICE_MIXING_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_RICE_MIXING_FINISH_DETAIL> TSPL_RICE_MIXING_FINISH_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_RICE_PROCESSING_DETAIL> TSPL_RICE_PROCESSING_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_RICE_PROCESSING_FINISH_DETAIL> TSPL_RICE_PROCESSING_FINISH_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_SALE_RETURN_GATE_ENTRY_DETAIL> TSPL_SALE_RETURN_GATE_ENTRY_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_SD_SALE_INVOICE_DETAIL> TSPL_SD_SALE_INVOICE_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_SD_SALE_RETURN_DETAIL> TSPL_SD_SALE_RETURN_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_SD_SALES_ORDER_DETAIL> TSPL_SD_SALES_ORDER_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_SD_SHIPMENT_DETAIL> TSPL_SD_SHIPMENT_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_SD_SALE_INVOICE_DETAIL> TSPL_SD_SALE_INVOICE_DETAIL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_SD_SALE_INVOICE_DETAIL> TSPL_SD_SALE_INVOICE_DETAIL2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_SD_SALES_ORDER_DETAIL> TSPL_SD_SALES_ORDER_DETAIL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_SD_SALES_ORDER_DETAIL> TSPL_SD_SALES_ORDER_DETAIL2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_SD_SHIPMENT_DETAIL> TSPL_SD_SHIPMENT_DETAIL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_SD_SHIPMENT_DETAIL> TSPL_SD_SHIPMENT_DETAIL2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_SD_SHIPMENT_DETAIL> TSPL_SD_SHIPMENT_DETAIL3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_SD_SALE_INVOICE_DETAIL> TSPL_SD_SALE_INVOICE_DETAIL3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_SD_SALE_RETURN_DETAIL> TSPL_SD_SALE_RETURN_DETAIL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_SD_SALES_ORDER_DETAIL> TSPL_SD_SALES_ORDER_DETAIL3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_SILO_MILK_TRANSFER_DETAIL> TSPL_SILO_MILK_TRANSFER_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_SPP_COST_WITHOUT_BATCH> TSPL_SPP_COST_WITHOUT_BATCH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_SPP_CONSUMPTION_WITHOUT_BATCH> TSPL_SPP_CONSUMPTION_WITHOUT_BATCH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_SPP_PE_WRECKAGE_FLASHING> TSPL_SPP_PE_WRECKAGE_FLASHING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_SPP_PE_STAGE_DETAIL> TSPL_SPP_PE_STAGE_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_SPP_PE_ISSUE_ITEM_DETAIL> TSPL_SPP_PE_ISSUE_ITEM_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_SPP_CONSUMPTION_WITHOUT_BATCH> TSPL_SPP_CONSUMPTION_WITHOUT_BATCH1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_SPP_PRODUCTION_ENTRY_DETAIL> TSPL_SPP_PRODUCTION_ENTRY_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_SPP_PE_SCRAP_DETAIL> TSPL_SPP_PE_SCRAP_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_TANKER_MASTER_SALE_DETAIL> TSPL_TANKER_MASTER_SALE_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_VLC_MASTER_HEAD> TSPL_VLC_MASTER_HEAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_WRECKAGE_BOOKING> TSPL_WRECKAGE_BOOKING { get; set; }
    }
}
