//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_JOB_OUTWARD_PRICE_DETAIL
    {
        public string Price_Code { get; set; }
        public string ItemCode { get; set; }
        public string ItemDesc { get; set; }
        public string ItemUom { get; set; }
        public Nullable<decimal> Charges { get; set; }
        public string RM_Item_Code { get; set; }
    
        public virtual TSPL_ITEM_MASTER TSPL_ITEM_MASTER { get; set; }
        public virtual TSPL_JOB_OUTWARD_PRICE_HEAD TSPL_JOB_OUTWARD_PRICE_HEAD { get; set; }
    }
}
