//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_ACQUISITION_SRN_HEAD
    {
        public string Acquisition_Code { get; set; }
        public string SRN_No { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Item_Code { get; set; }
        public string Item_Name { get; set; }
        public int SRN_QTY { get; set; }
        public decimal Unit_Rate { get; set; }
        public string Unit_Code { get; set; }
        public int lineNo { get; set; }
        public string PI_No { get; set; }
    
        public virtual TSPL_PI_HEAD TSPL_PI_HEAD { get; set; }
        public virtual TSPL_SRN_HEAD TSPL_SRN_HEAD { get; set; }
    }
}
