//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_JOURNAL_DETAILS
    {
        public int Journal_No { get; set; }
        public string Voucher_No { get; set; }
        public Nullable<System.DateTime> Voucher_Date { get; set; }
        public int Detail_Line_No { get; set; }
        public string Account_code { get; set; }
        public string Account_Desc { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Description { get; set; }
        public string Reference { get; set; }
        public Nullable<System.DateTime> Posting_Date { get; set; }
        public string Account_Type { get; set; }
        public string Account_Group_Code { get; set; }
        public string Account_Seg_Code1 { get; set; }
        public string Account_Seg_Desc1 { get; set; }
        public string Account_Seg_Code2 { get; set; }
        public string Account_Seg_Desc2 { get; set; }
        public string Account_Seg_Code3 { get; set; }
        public string Account_Seg_Desc3 { get; set; }
        public string Account_Seg_Code4 { get; set; }
        public string Account_Seg_Desc4 { get; set; }
        public string Account_Seg_Code5 { get; set; }
        public string Account_Seg_Desc5 { get; set; }
        public string Account_Seg_Code6 { get; set; }
        public string Account_Seg_Desc6 { get; set; }
        public string Account_Seg_Code7 { get; set; }
        public string Account_Seg_Desc7 { get; set; }
        public string Account_Seg_Code8 { get; set; }
        public string Account_Seg_Desc8 { get; set; }
        public string Account_Seg_Code9 { get; set; }
        public string Account_Seg_Desc9 { get; set; }
        public string Account_Seg_Code10 { get; set; }
        public string Account_Seg_Desc10 { get; set; }
        public string CustVend_Code { get; set; }
        public string CustVend_Name { get; set; }
        public int PK_Id { get; set; }
        public string Hirerachy_Code { get; set; }
        public string Cost_Centre_Code { get; set; }
        public string Reco_Control_Account { get; set; }
        public string Hirerachy_Code3 { get; set; }
        public string Hirerachy_Code4 { get; set; }
    
        public virtual TSPL_COST_CENTRE_FINANCIAL TSPL_COST_CENTRE_FINANCIAL { get; set; }
        public virtual TSPL_COST_CENTRE_FINANCIAL TSPL_COST_CENTRE_FINANCIAL1 { get; set; }
        public virtual TSPL_COST_CENTRE_FINANCIAL TSPL_COST_CENTRE_FINANCIAL2 { get; set; }
        public virtual TSPL_HIRERACHY_LEVEL_MASTER TSPL_HIRERACHY_LEVEL_MASTER { get; set; }
        public virtual TSPL_JOURNAL_MASTER TSPL_JOURNAL_MASTER { get; set; }
    }
}
