//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_ONDEMAND_DISTATCH_DETAIL
    {
        public string Document_Code { get; set; }
        public string Shift { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> Document_Date { get; set; }
        public Nullable<System.DateTime> From_Time { get; set; }
        public Nullable<System.DateTime> To_Time { get; set; }
        public Nullable<System.DateTime> Order_From_Time { get; set; }
        public Nullable<System.DateTime> Order_To_Time { get; set; }
        public Nullable<System.DateTime> Payment_From_Time { get; set; }
        public Nullable<System.DateTime> Payment_To_Time { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Modified_By { get; set; }
        public System.DateTime Modified_Date { get; set; }
    
        public virtual TSPL_USER_MASTER TSPL_USER_MASTER { get; set; }
        public virtual TSPL_USER_MASTER TSPL_USER_MASTER1 { get; set; }
    }
}
