//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_MCC_DISPATCH_TRANSFER
    {
        public string Doc_No { get; set; }
        public System.DateTime Doc_Date { get; set; }
        public string OLD_FROM_Loc_Code { get; set; }
        public string OLD_TO_LOC_TYPE { get; set; }
        public string OLD_TO_Loc_Code { get; set; }
        public string NEW_TO_LOC_TYPE { get; set; }
        public string NEW_TO_Loc_Code { get; set; }
        public string Challan_No { get; set; }
        public string Comp_Code { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Modified_By { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public int isPosted { get; set; }
        public Nullable<System.DateTime> Posting_Date { get; set; }
    }
}
