//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_HR_TRAVEL_MODE_TYPE_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSPL_HR_TRAVEL_MODE_TYPE_MASTER()
        {
            this.TSPL_HR_RAISE_TRAVEL_REQUISITION_ENTRY = new HashSet<TSPL_HR_RAISE_TRAVEL_REQUISITION_ENTRY>();
            this.TSPL_HR_TRAVEL_CLASS_TYPE_MASTER = new HashSet<TSPL_HR_TRAVEL_CLASS_TYPE_MASTER>();
        }
    
        public string Travel_Mode_Code { get; set; }
        public string Description { get; set; }
        public int Is_Applicable { get; set; }
        public string Comp_Code { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Modified_By { get; set; }
        public System.DateTime Modified_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_HR_RAISE_TRAVEL_REQUISITION_ENTRY> TSPL_HR_RAISE_TRAVEL_REQUISITION_ENTRY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_HR_TRAVEL_CLASS_TYPE_MASTER> TSPL_HR_TRAVEL_CLASS_TYPE_MASTER { get; set; }
    }
}
