//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_CHEQUE_SETTING
    {
        public string BCODE { get; set; }
        public Nullable<int> CodeValue { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> FrmTop { get; set; }
        public Nullable<decimal> FrmHeight { get; set; }
        public Nullable<decimal> FrmLeft { get; set; }
        public Nullable<decimal> FrmWidth { get; set; }
        public string FontName { get; set; }
        public Nullable<decimal> FontSize { get; set; }
        public Nullable<int> isBold { get; set; }
        public Nullable<int> CharPerLine { get; set; }
        public Nullable<int> DecimalPlaces { get; set; }
        public Nullable<decimal> PageTop { get; set; }
        public Nullable<decimal> PageLeft { get; set; }
        public string DateStyle { get; set; }
        public Nullable<int> PaperOrientation { get; set; }
        public int IsVisible { get; set; }
        public int isxxxxxxBefore { get; set; }
        public int isxxxxxxAfter { get; set; }
        public int CharSpace { get; set; }
    }
}
