//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_RECEIPT_INVOICEMAPPING_DETAIL
    {
        public string Doc_CODE { get; set; }
        public string Line_No { get; set; }
        public string InvoiceNo { get; set; }
        public string Remarks { get; set; }
        public string InvoiceLocation { get; set; }
        public decimal Total_Tax_Amt { get; set; }
        public decimal Tax1_Amt { get; set; }
        public decimal Tax2_Amt { get; set; }
        public decimal Tax3_Amt { get; set; }
        public decimal Tax4_Amt { get; set; }
        public decimal Tax5_Amt { get; set; }
        public decimal Tax6_Amt { get; set; }
        public decimal Tax7_Amt { get; set; }
        public decimal Tax8_Amt { get; set; }
        public decimal Tax9_Amt { get; set; }
        public decimal Tax10_Amt { get; set; }
    
        public virtual TSPL_RECEIPT_INVOICEMAPPING_HEAD TSPL_RECEIPT_INVOICEMAPPING_HEAD { get; set; }
        public virtual TSPL_SD_SALE_INVOICE_HEAD TSPL_SD_SALE_INVOICE_HEAD { get; set; }
    }
}
