//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_NRGP_REQUEST_DETAIL
    {
        public string BOOKING_NO { get; set; }
        public int Line_No { get; set; }
        public string CSA_ITEM_TYPE { get; set; }
        public double BOOK_QTY { get; set; }
        public string BOOK_QTY_UOM { get; set; }
        public string TAX_PAID { get; set; }
        public double BOOK_Rate { get; set; }
        public string BOOK_RATE_UOM { get; set; }
        public double TOTAL_QTY { get; set; }
        public string Item_Code { get; set; }
    
        public virtual TSPL_ITEM_MASTER TSPL_ITEM_MASTER { get; set; }
        public virtual TSPL_NRGP_REQUEST_HEAD TSPL_NRGP_REQUEST_HEAD { get; set; }
        public virtual TSPL_UNIT_MASTER TSPL_UNIT_MASTER { get; set; }
        public virtual TSPL_UNIT_MASTER TSPL_UNIT_MASTER1 { get; set; }
    }
}
