//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_MF_PRINCIPLE_RECEIPT_SERIAL_DETAIL
    {
        public string Doc_No { get; set; }
        public int Sno { get; set; }
        public string Location_Code { get; set; }
        public string Main_Item_Code { get; set; }
        public string Main_Serial_No { get; set; }
        public string bom_code { get; set; }
        public string issue_code { get; set; }
        public string Item_Code { get; set; }
        public string Unit_Code { get; set; }
        public Nullable<double> Rec_Qty { get; set; }
        public string Serial_No { get; set; }
        public string Remarks { get; set; }
        public string Is_principle { get; set; }
    
        public virtual TSPL_ITEM_MASTER TSPL_ITEM_MASTER { get; set; }
        public virtual TSPL_ITEM_MASTER TSPL_ITEM_MASTER1 { get; set; }
        public virtual TSPL_MF_PRINCIPLE_RECEIPT_HEAD TSPL_MF_PRINCIPLE_RECEIPT_HEAD { get; set; }
    }
}
