//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_TEMPLATE_EXPIMP_HEAD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSPL_TEMPLATE_EXPIMP_HEAD()
        {
            this.TSPL_TEMPLATE_EXPIMP_DETAIL = new HashSet<TSPL_TEMPLATE_EXPIMP_DETAIL>();
        }
    
        public string Export_Code { get; set; }
        public string Program_Code { get; set; }
        public string Template_Name { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modify_By { get; set; }
        public Nullable<System.DateTime> Modify_Date { get; set; }
        public string Comp_Code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_TEMPLATE_EXPIMP_DETAIL> TSPL_TEMPLATE_EXPIMP_DETAIL { get; set; }
    }
}
