//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_PRODUCTION_UPLOADER_DETAIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSPL_PRODUCTION_UPLOADER_DETAIL()
        {
            this.TSPL_PP_PRODUCTION_PLAN_HEAD = new HashSet<TSPL_PP_PRODUCTION_PLAN_HEAD>();
        }
    
        public string Document_No { get; set; }
        public string TR_No { get; set; }
        public System.DateTime TR_Date { get; set; }
        public Nullable<int> SNo { get; set; }
        public string Section_Code { get; set; }
        public string Item_Code { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string UOM { get; set; }
        public string Shift_Code { get; set; }
        public int Status { get; set; }
    
        public virtual TSPL_ITEM_MASTER TSPL_ITEM_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PP_PRODUCTION_PLAN_HEAD> TSPL_PP_PRODUCTION_PLAN_HEAD { get; set; }
        public virtual TSPL_PRODUCTION_UPLOADER_HEAD TSPL_PRODUCTION_UPLOADER_HEAD { get; set; }
        public virtual TSPL_SECTION_MASTER TSPL_SECTION_MASTER { get; set; }
        public virtual TSPL_SHIFT_MASTER TSPL_SHIFT_MASTER { get; set; }
    }
}
