//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_INCENTIVE_ENTRY_BY_SRN_HEAD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSPL_INCENTIVE_ENTRY_BY_SRN_HEAD()
        {
            this.TSPL_INCENTIVE_ENTRY_BY_SRN_DETAIL = new HashSet<TSPL_INCENTIVE_ENTRY_BY_SRN_DETAIL>();
        }
    
        public string Doc_Code { get; set; }
        public System.DateTime Doc_Date { get; set; }
        public string MCC_Code { get; set; }
        public System.DateTime Filter_Month { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Modified_By { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public int Is_Post { get; set; }
        public string Post_By { get; set; }
        public Nullable<System.DateTime> Post_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_INCENTIVE_ENTRY_BY_SRN_DETAIL> TSPL_INCENTIVE_ENTRY_BY_SRN_DETAIL { get; set; }
        public virtual TSPL_MCC_MASTER TSPL_MCC_MASTER { get; set; }
    }
}
