//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_TERMS_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSPL_TERMS_MASTER()
        {
            this.TSPL_SALES_ORDER_MASTER_BULKSALE = new HashSet<TSPL_SALES_ORDER_MASTER_BULKSALE>();
        }
    
        public string Terms_Code { get; set; }
        public string Terms_Desc { get; set; }
        public int No_Days { get; set; }
        public string Created_By { get; set; }
        public string Created_Date { get; set; }
        public string Modify_By { get; set; }
        public string Modify_Date { get; set; }
        public string Comp_Code { get; set; }
        public int LCRequired { get; set; }
        public int isAdvance { get; set; }
        public decimal Advance_Per { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_SALES_ORDER_MASTER_BULKSALE> TSPL_SALES_ORDER_MASTER_BULKSALE { get; set; }
    }
}
