//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tspl_SettleMent_Master
    {
        public string SettleMentCode { get; set; }
        public string Description { get; set; }
        public string Created_By { get; set; }
        public string Created_Date { get; set; }
        public string Modify_By { get; set; }
        public string Modify_Date { get; set; }
        public string Comp_Code { get; set; }
        public string Calculate { get; set; }
        public string Account_Code { get; set; }
        public string Account_Description { get; set; }
        public int Sequence_No { get; set; }
        public string SettleMent_Type { get; set; }
        public string Type { get; set; }
        public string Financial_Entry { get; set; }
    }
}
