//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_PAYROLL_SETTING_INHAND_DETAIL
    {
        public string PAY_SETTING_CODE { get; set; }
        public string PAY_HEAD_CODE { get; set; }
    
        public virtual TSPL_PAYHEAD_MASTER TSPL_PAYHEAD_MASTER { get; set; }
        public virtual TSPL_PAYROLL_SETTING TSPL_PAYROLL_SETTING { get; set; }
    }
}
