//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_DAILY_ELECTRICAL_ENTRY_DG_DETAILS
    {
        public string Document_No { get; set; }
        public Nullable<int> SNo { get; set; }
        public string DG_Code { get; set; }
        public Nullable<decimal> DG_Unit { get; set; }
        public Nullable<decimal> DG_Consumption { get; set; }
        public Nullable<decimal> DG_Runing_Hours { get; set; }
    
        public virtual TSPL_DAILY_ELECTRICAL_ENTRY_HEAD TSPL_DAILY_ELECTRICAL_ENTRY_HEAD { get; set; }
        public virtual TSPL_DG_MASTER TSPL_DG_MASTER { get; set; }
    }
}
