//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_BulkSalePrice_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSPL_BulkSalePrice_MASTER()
        {
            this.TSPL_BulkSalePrice_MASTER_History = new HashSet<TSPL_BulkSalePrice_MASTER_History>();
            this.TSPL_CAN_SALE_HEAD = new HashSet<TSPL_CAN_SALE_HEAD>();
            this.TSPL_CANSALE_DISPATCH_HEAD = new HashSet<TSPL_CANSALE_DISPATCH_HEAD>();
            this.TSPL_CANSALE_INVOICE_HEAD = new HashSet<TSPL_CANSALE_INVOICE_HEAD>();
            this.TSPL_Dispatch_BulkSale = new HashSet<TSPL_Dispatch_BulkSale>();
            this.TSPL_Dispatch_BulkSale_Trade = new HashSet<TSPL_Dispatch_BulkSale_Trade>();
            this.TSPL_DISPATCH_BULKSALE_TRADE_RETURN = new HashSet<TSPL_DISPATCH_BULKSALE_TRADE_RETURN>();
            this.TSPL_SALES_ORDER_MASTER_BULKSALE = new HashSet<TSPL_SALES_ORDER_MASTER_BULKSALE>();
            this.TSPL_SALES_ORDER_DETAIL_BULKSALE = new HashSet<TSPL_SALES_ORDER_DETAIL_BULKSALE>();
        }
    
        public string Price_Code { get; set; }
        public System.DateTime Price_Date { get; set; }
        public decimal Fat_Weightage { get; set; }
        public decimal Snf_Weightage { get; set; }
        public decimal Standard_Rate { get; set; }
        public string Comp_Code { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Modified_By { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public decimal Fat_Ratio { get; set; }
        public decimal Snf_Ratio { get; set; }
        public string Location_Code { get; set; }
        public double FatRate { get; set; }
        public double SNFRate { get; set; }
        public double TolerancePerPlus { get; set; }
        public double TolerancePerMinus { get; set; }
        public int AbandonmentNo { get; set; }
        public Nullable<System.DateTime> ValidTill { get; set; }
        public int Posted { get; set; }
        public string Posted_By { get; set; }
        public Nullable<System.DateTime> Posted_Date { get; set; }
        public int UseInCanSale { get; set; }
        public Nullable<decimal> TSRate { get; set; }
        public string UOM { get; set; }
    
        public virtual TSPL_LOCATION_MASTER TSPL_LOCATION_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_BulkSalePrice_MASTER_History> TSPL_BulkSalePrice_MASTER_History { get; set; }
        public virtual TSPL_UNIT_MASTER TSPL_UNIT_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_CAN_SALE_HEAD> TSPL_CAN_SALE_HEAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_CANSALE_DISPATCH_HEAD> TSPL_CANSALE_DISPATCH_HEAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_CANSALE_INVOICE_HEAD> TSPL_CANSALE_INVOICE_HEAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_Dispatch_BulkSale> TSPL_Dispatch_BulkSale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_Dispatch_BulkSale_Trade> TSPL_Dispatch_BulkSale_Trade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_DISPATCH_BULKSALE_TRADE_RETURN> TSPL_DISPATCH_BULKSALE_TRADE_RETURN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_SALES_ORDER_MASTER_BULKSALE> TSPL_SALES_ORDER_MASTER_BULKSALE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_SALES_ORDER_DETAIL_BULKSALE> TSPL_SALES_ORDER_DETAIL_BULKSALE { get; set; }
    }
}
