//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_PRICE_CHART_PLANNING_TOTAL_SOLID
    {
        public string Planning_Code { get; set; }
        public Nullable<decimal> Min_Range { get; set; }
        public Nullable<decimal> Value { get; set; }
    
        public virtual TSPL_PRICE_CHART_PLANNING TSPL_PRICE_CHART_PLANNING { get; set; }
    }
}
