//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_EMPLOYEE_LANGUAGES
    {
        public string EMP_CODE { get; set; }
        public int LINE_NO { get; set; }
        public string LANGUAGE_CODE { get; set; }
        public string READING_LEVEL { get; set; }
        public string WRITTING_LEVEL { get; set; }
        public string SPEAKING_LEVEL { get; set; }
        public string DESCRIPTION { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Modified_By { get; set; }
        public System.DateTime Modified_Date { get; set; }
    
        public virtual TSPL_EMPLOYEE_MASTER TSPL_EMPLOYEE_MASTER { get; set; }
        public virtual TSPL_LANGUAGE_MASTER TSPL_LANGUAGE_MASTER { get; set; }
    }
}
