//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_WS_CARD_SALE_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSPL_WS_CARD_SALE_MASTER()
        {
            this.TSPL_WS_CARD_SALE_DETAIL = new HashSet<TSPL_WS_CARD_SALE_DETAIL>();
        }
    
        public string Document_No { get; set; }
        public System.DateTime Document_Date { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Cust_Code { get; set; }
        public string location_code { get; set; }
        public int IsSampling { get; set; }
        public string Booking_Type { get; set; }
        public string Card_SALE_No { get; set; }
        public Nullable<System.DateTime> CardSale_FROM_DATE { get; set; }
        public Nullable<System.DateTime> CardSale_TO_DATE { get; set; }
        public string Payment_Mode { get; set; }
        public string Against_Booking_No { get; set; }
        public string Against_Receipt_No { get; set; }
        public string Transaction_ID { get; set; }
        public double AdvanceAmount { get; set; }
        public string Created_By { get; set; }
    
        public virtual TSPL_CARD_SALE TSPL_CARD_SALE { get; set; }
        public virtual TSPL_RECEIPT_HEADER TSPL_RECEIPT_HEADER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_WS_CARD_SALE_DETAIL> TSPL_WS_CARD_SALE_DETAIL { get; set; }
    }
}
