//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_PAYMENT_PROCESS_HEAD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSPL_PAYMENT_PROCESS_HEAD()
        {
            this.TSPL_MCC_PAYMENT_CYCLE_LOCK_FOR_SCHEDULER = new HashSet<TSPL_MCC_PAYMENT_CYCLE_LOCK_FOR_SCHEDULER>();
            this.TSPL_MP_PAY_HEAD = new HashSet<TSPL_MP_PAY_HEAD>();
            this.TSPL_MP_PAY_PROCESS_DETAIL = new HashSet<TSPL_MP_PAY_PROCESS_DETAIL>();
            this.TSPL_PAYMENT_PROCESS_DETAIL = new HashSet<TSPL_PAYMENT_PROCESS_DETAIL>();
            this.TSPL_PAYMENT_PROCESS_ADVANCE_PAYMENT = new HashSet<TSPL_PAYMENT_PROCESS_ADVANCE_PAYMENT>();
            this.TSPL_PAYMENT_PROCESS_ASSET_LOST = new HashSet<TSPL_PAYMENT_PROCESS_ASSET_LOST>();
            this.TSPL_PAYMENT_PROCESS_FARMER_MP_ADVANCE = new HashSet<TSPL_PAYMENT_PROCESS_FARMER_MP_ADVANCE>();
            this.TSPL_PAYMENT_PROCESS_ADJ_DETAIL = new HashSet<TSPL_PAYMENT_PROCESS_ADJ_DETAIL>();
            this.TSPL_PAYMENT_PROCESS_SKIP_DOCUMENT = new HashSet<TSPL_PAYMENT_PROCESS_SKIP_DOCUMENT>();
        }
    
        public string Doc_No { get; set; }
        public System.DateTime Doc_Date { get; set; }
        public System.DateTime From_Date { get; set; }
        public System.DateTime To_Date { get; set; }
        public string Loc_Seg_Code { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Modified_By { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public string Comp_Code { get; set; }
        public int isPosted { get; set; }
        public Nullable<System.DateTime> Posting_Date { get; set; }
        public string DocRefNoForUploader { get; set; }
        public string PaymentDesc { get; set; }
        public int Is_Skip_Previous_Item_Issue { get; set; }
        public int Is_Skip_Previous_Item_Issue_Return { get; set; }
        public int Is_Skip_Previous_MCC_Sale { get; set; }
        public int Is_Skip_Previous_MCC_Sale_Return { get; set; }
        public int Is_Skip_Previous_Credit_Note { get; set; }
        public int Is_Skip_Previous_Debit_Note { get; set; }
        public int Is_Skip_Previous_Advacee_Payment { get; set; }
        public string FarmType { get; set; }
        public string MCC_Code_Selected { get; set; }
    
        public virtual TSPL_COMPANY_MASTER TSPL_COMPANY_MASTER { get; set; }
        public virtual TSPL_MCC_MASTER TSPL_MCC_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MCC_PAYMENT_CYCLE_LOCK_FOR_SCHEDULER> TSPL_MCC_PAYMENT_CYCLE_LOCK_FOR_SCHEDULER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MP_PAY_HEAD> TSPL_MP_PAY_HEAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MP_PAY_PROCESS_DETAIL> TSPL_MP_PAY_PROCESS_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PAYMENT_PROCESS_DETAIL> TSPL_PAYMENT_PROCESS_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PAYMENT_PROCESS_ADVANCE_PAYMENT> TSPL_PAYMENT_PROCESS_ADVANCE_PAYMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PAYMENT_PROCESS_ASSET_LOST> TSPL_PAYMENT_PROCESS_ASSET_LOST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PAYMENT_PROCESS_FARMER_MP_ADVANCE> TSPL_PAYMENT_PROCESS_FARMER_MP_ADVANCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PAYMENT_PROCESS_ADJ_DETAIL> TSPL_PAYMENT_PROCESS_ADJ_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_PAYMENT_PROCESS_SKIP_DOCUMENT> TSPL_PAYMENT_PROCESS_SKIP_DOCUMENT { get; set; }
    }
}
