//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_AP_INVOICE_ADVANCE_INTEREST
    {
        public string AP_Invoice_No { get; set; }
        public string Payment_No { get; set; }
        public Nullable<decimal> Interest_Amount { get; set; }
    
        public virtual TSPL_PAYMENT_HEADER TSPL_PAYMENT_HEADER { get; set; }
        public virtual TSPL_VENDOR_INVOICE_HEAD TSPL_VENDOR_INVOICE_HEAD { get; set; }
    }
}
