//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_ES_CONTENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSPL_ES_CONTENT()
        {
            this.TSPL_ES_CONTENT_EMP_DETAIL = new HashSet<TSPL_ES_CONTENT_EMP_DETAIL>();
        }
    
        public string Form_Id { get; set; }
        public string EMail_Subject { get; set; }
        public string EMail_Text { get; set; }
        public string SMS_Text { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Modified_By { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public string Notification_Caption { get; set; }
        public string Notification_Text { get; set; }
        public string Notification_On { get; set; }
        public string Notification_Detail_Text { get; set; }
        public Nullable<int> No_Of_Char { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_ES_CONTENT_EMP_DETAIL> TSPL_ES_CONTENT_EMP_DETAIL { get; set; }
    }
}
