//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_OT_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSPL_OT_MASTER()
        {
            this.TSPL_ATTENDANCE_MASTER = new HashSet<TSPL_ATTENDANCE_MASTER>();
            this.TSPL_EMPLOYEE_STATUS = new HashSet<TSPL_EMPLOYEE_STATUS>();
            this.TSPL_GENERATE_SALARY_PAYHEADS = new HashSet<TSPL_GENERATE_SALARY_PAYHEADS>();
            this.TSPL_OT_SHEET = new HashSet<TSPL_OT_SHEET>();
        }
    
        public string OT_CODE { get; set; }
        public string OT_NAME { get; set; }
        public double HOUR_MULTIPLIER { get; set; }
        public double OT_RATE { get; set; }
        public bool IS_ASPER_ACTUAL_CALC { get; set; }
        public string DESCRIPTION { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Modified_By { get; set; }
        public System.DateTime Modified_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_ATTENDANCE_MASTER> TSPL_ATTENDANCE_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_EMPLOYEE_STATUS> TSPL_EMPLOYEE_STATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_GENERATE_SALARY_PAYHEADS> TSPL_GENERATE_SALARY_PAYHEADS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_OT_SHEET> TSPL_OT_SHEET { get; set; }
        public virtual TSPL_OT_SLAB_DETAIL TSPL_OT_SLAB_DETAIL { get; set; }
    }
}
