//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_FORMISSUE_HEAD
    {
        public string FormIssue_no { get; set; }
        public string DemandNo { get; set; }
        public Nullable<System.DateTime> Demand_Date { get; set; }
        public string FormCode { get; set; }
        public string FormName { get; set; }
        public string FormSeries { get; set; }
        public int FromNo { get; set; }
        public int ToNo { get; set; }
        public int TotalForms { get; set; }
        public string Remarks { get; set; }
        public string Comments { get; set; }
        public string Created_By { get; set; }
        public string Created_Date { get; set; }
        public string Modify_By { get; set; }
        public string Modify_Date { get; set; }
        public string Comp_Code { get; set; }
    }
}
