//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_MCC_WEIGHMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSPL_MCC_WEIGHMENT()
        {
            this.TSPL_MCC_Dispatch_Challan = new HashSet<TSPL_MCC_Dispatch_Challan>();
            this.TSPL_MCC_TANKER_DISPATCH_RETURN_HEAD = new HashSet<TSPL_MCC_TANKER_DISPATCH_RETURN_HEAD>();
        }
    
        public string Document_No { get; set; }
        public System.DateTime Document_Date { get; set; }
        public string Gate_Entry_No { get; set; }
        public string Location_Code { get; set; }
        public Nullable<decimal> Tare_Weight { get; set; }
        public Nullable<decimal> Gross_Weight { get; set; }
        public Nullable<decimal> Net_Weight { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Modified_By { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public int Status_Tare_Weight { get; set; }
        public Nullable<System.DateTime> Post_Date_Tare_Weight { get; set; }
        public string Post_By_Tare_Weight { get; set; }
        public int Status_Gross_Weight { get; set; }
        public Nullable<System.DateTime> Post_Date_Gross_Weight { get; set; }
        public string Post_By_Gross_Weight { get; set; }
    
        public virtual TSPL_LOCATION_MASTER TSPL_LOCATION_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MCC_Dispatch_Challan> TSPL_MCC_Dispatch_Challan { get; set; }
        public virtual TSPL_MCC_GATE_ENTRY TSPL_MCC_GATE_ENTRY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MCC_TANKER_DISPATCH_RETURN_HEAD> TSPL_MCC_TANKER_DISPATCH_RETURN_HEAD { get; set; }
    }
}
