//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_MP_INCENTIVE_ENTRY_VLC_STATUS
    {
        public int PK_Id { get; set; }
        public string Document_Code { get; set; }
        public string VLC_Code { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
    
        public virtual TSPL_MP_INCENTIVE_ENTRY_HEAD TSPL_MP_INCENTIVE_ENTRY_HEAD { get; set; }
        public virtual TSPL_VLC_MASTER_HEAD TSPL_VLC_MASTER_HEAD { get; set; }
    }
}
