//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_MILK_COLLECTION_MCC_MULTIPLE_DAYS_DETAIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSPL_MILK_COLLECTION_MCC_MULTIPLE_DAYS_DETAIL()
        {
            this.TSPL_MILK_COLLECTION_MCC_DETAIL = new HashSet<TSPL_MILK_COLLECTION_MCC_DETAIL>();
        }
    
        public int PK_Id { get; set; }
        public System.DateTime Collection_Date { get; set; }
        public string Document_No { get; set; }
        public Nullable<int> SNo { get; set; }
        public string MCC_Code { get; set; }
        public string Milk_Type { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> FAT { get; set; }
        public Nullable<decimal> SNF { get; set; }
        public Nullable<decimal> FATKG { get; set; }
        public Nullable<decimal> SNFKG { get; set; }
        public Nullable<decimal> Gaze_Reading { get; set; }
        public Nullable<int> Silo_Capacity { get; set; }
        public Nullable<decimal> Temp { get; set; }
        public Nullable<int> Sample_No { get; set; }
        public string Gaze_Reading_Code { get; set; }
        public int IsUpdatedFromCorrection { get; set; }
    
        public virtual TSPL_GAZE_READING TSPL_GAZE_READING { get; set; }
        public virtual TSPL_MCC_MASTER TSPL_MCC_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MILK_COLLECTION_MCC_DETAIL> TSPL_MILK_COLLECTION_MCC_DETAIL { get; set; }
        public virtual TSPL_MILK_COLLECTION_MCC_MULTIPLE_DAYS TSPL_MILK_COLLECTION_MCC_MULTIPLE_DAYS { get; set; }
    }
}
