//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_CONTRACT_TANKER_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSPL_CONTRACT_TANKER_MASTER()
        {
            this.TSPL_CONTRACT_TANKER_DETAIL = new HashSet<TSPL_CONTRACT_TANKER_DETAIL>();
        }
    
        public string Created_By { get; set; }
        public string TANKER_CODE { get; set; }
        public string TANKER_NO { get; set; }
        public double NO_OF_CHAMBER { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Modified_By { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public string Comp_Code { get; set; }
        public string Vendor_Code { get; set; }
    
        public virtual TSPL_COMPANY_MASTER TSPL_COMPANY_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_CONTRACT_TANKER_DETAIL> TSPL_CONTRACT_TANKER_DETAIL { get; set; }
        public virtual TSPL_CONTRACT_TANKER_VENDOR_DETAIL TSPL_CONTRACT_TANKER_VENDOR_DETAIL { get; set; }
        public virtual TSPL_VENDOR_MASTER TSPL_VENDOR_MASTER { get; set; }
    }
}
