//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_Item_Tax
    {
        public string Item_Code { get; set; }
        public string Unit_Code { get; set; }
        public Nullable<decimal> Excise { get; set; }
        public Nullable<decimal> Ecess { get; set; }
        public Nullable<decimal> Hcess { get; set; }
        public string Tax_Code_Excise { get; set; }
        public string Tax_Code_Ecess { get; set; }
        public string Tax_Code_Hcess { get; set; }
    
        public virtual TSPL_TAX_MASTER TSPL_TAX_MASTER { get; set; }
        public virtual TSPL_TAX_MASTER TSPL_TAX_MASTER1 { get; set; }
        public virtual TSPL_TAX_MASTER TSPL_TAX_MASTER2 { get; set; }
    }
}
