//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_CUSTOMER_ITEM_DETAIL_HIST
    {
        public string Customer_Code { get; set; }
        public string Customer_Desc { get; set; }
        public string item_no { get; set; }
        public string item_desc { get; set; }
        public string uom { get; set; }
        public Nullable<decimal> item_rate { get; set; }
        public string Customer_item_no { get; set; }
        public string Comp_Code { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public Nullable<System.DateTime> History_Date { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<decimal> Item_MRP { get; set; }
    }
}
