//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_PAYMENT_BANK_CHARGES_TAX
    {
        public string Payment_No { get; set; }
        public Nullable<int> Line_No { get; set; }
        public string Tax_Code { get; set; }
        public Nullable<decimal> Tax_Rate { get; set; }
        public Nullable<decimal> Tax_Base_Amount { get; set; }
        public Nullable<decimal> Tax_Amount { get; set; }
    
        public virtual TSPL_PAYMENT_HEADER TSPL_PAYMENT_HEADER { get; set; }
        public virtual TSPL_TAX_MASTER TSPL_TAX_MASTER { get; set; }
    }
}
