//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_CAN_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSPL_CAN_MASTER()
        {
            this.TSPL_MILK_RECEIPT_DETAIL_SYNC = new HashSet<TSPL_MILK_RECEIPT_DETAIL_SYNC>();
            this.TSPL_MILK_RECEIPT_DETAIL = new HashSet<TSPL_MILK_RECEIPT_DETAIL>();
        }
    
        public string Code { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Tare_Weight { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Modify_By { get; set; }
        public System.DateTime Modify_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MILK_RECEIPT_DETAIL_SYNC> TSPL_MILK_RECEIPT_DETAIL_SYNC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MILK_RECEIPT_DETAIL> TSPL_MILK_RECEIPT_DETAIL { get; set; }
    }
}
