//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_MILK_SAMPLE_DETAIL
    {
        public string DOC_CODE { get; set; }
        public string VLC_DOC_CODE { get; set; }
        public int SAMPLE_NO { get; set; }
        public string MILK_TYPE { get; set; }
        public string TYPE { get; set; }
        public string VSP_CODE { get; set; }
        public decimal Qty { get; set; }
        public decimal FAT { get; set; }
        public decimal SNF { get; set; }
        public decimal CLR { get; set; }
        public decimal RATE { get; set; }
        public decimal AMOUNT { get; set; }
        public decimal Correction_Factor { get; set; }
        public string IS_MANUAL { get; set; }
        public string Item_Code { get; set; }
        public string MILK_SRN_CODE { get; set; }
        public string UOM_Code { get; set; }
        public decimal ACC_Qty { get; set; }
        public decimal Commission_Pers { get; set; }
        public decimal EMP_Pers { get; set; }
        public decimal Commission_Amount { get; set; }
        public decimal EMP_Amount { get; set; }
        public decimal NET_AMOUNT { get; set; }
        public decimal FAT_KG { get; set; }
        public decimal SNF_KG { get; set; }
        public string Price_Code { get; set; }
        public int PK_Id { get; set; }
        public Nullable<decimal> FAT_ORG { get; set; }
        public Nullable<decimal> SNF_ORG { get; set; }
        public Nullable<decimal> FAT_CORRECTION { get; set; }
        public Nullable<decimal> SNF_CORRECTION { get; set; }
        public Nullable<decimal> QAT_Rate { get; set; }
        public Nullable<decimal> Negative_Rate { get; set; }
    
        public virtual TSPL_ITEM_MASTER TSPL_ITEM_MASTER { get; set; }
        public virtual TSPL_MILK_SAMPLE_HEAD TSPL_MILK_SAMPLE_HEAD { get; set; }
        public virtual TSPL_VENDOR_MASTER TSPL_VENDOR_MASTER { get; set; }
    }
}
