//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_SPP_PE_WRECKAGE_FLASHING
    {
        public string PROD_ENTRY_CODE { get; set; }
        public Nullable<int> SNO { get; set; }
        public string Item_Code { get; set; }
        public string Unit_Code { get; set; }
        public Nullable<double> BACK_QTY { get; set; }
        public Nullable<double> WRECKAGE_QTY { get; set; }
        public string Location_Code { get; set; }
        public Nullable<double> Avail_FAT_Per { get; set; }
        public Nullable<double> Avail_SNF_Per { get; set; }
        public Nullable<double> Avail_FAT_KG { get; set; }
        public Nullable<double> Avail_SNF_KG { get; set; }
        public string Remarks { get; set; }
        public string Comp_Code { get; set; }
        public double Fat_Rate { get; set; }
        public double SNF_Rate { get; set; }
        public double Fat_Amt { get; set; }
        public double SNF_Amt { get; set; }
    
        public virtual TSPL_COMPANY_MASTER TSPL_COMPANY_MASTER { get; set; }
        public virtual TSPL_ITEM_MASTER TSPL_ITEM_MASTER { get; set; }
        public virtual TSPL_LOCATION_MASTER TSPL_LOCATION_MASTER { get; set; }
        public virtual TSPL_SPP_PRODUCTION_ENTRY TSPL_SPP_PRODUCTION_ENTRY { get; set; }
        public virtual TSPL_UNIT_MASTER TSPL_UNIT_MASTER { get; set; }
    }
}
