//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_ITEM_REORDER_LEVEL_NEW
    {
        public string Item_Code { get; set; }
        public Nullable<decimal> Min_Level { get; set; }
        public Nullable<int> Min_Level_Tollerence { get; set; }
        public Nullable<decimal> Max_Level { get; set; }
        public Nullable<int> Max_Level_Tollerence { get; set; }
        public Nullable<decimal> Reorder_Level { get; set; }
        public Nullable<int> Reorder_Level_Tollerence { get; set; }
        public string Apply { get; set; }
        public string comp_code { get; set; }
        public string Location_Code { get; set; }
        public decimal Reorder_Qty { get; set; }
        public string Uom_Code { get; set; }
    
        public virtual TSPL_ITEM_MASTER TSPL_ITEM_MASTER { get; set; }
        public virtual TSPL_LOCATION_MASTER TSPL_LOCATION_MASTER { get; set; }
        public virtual TSPL_UNIT_MASTER TSPL_UNIT_MASTER { get; set; }
    }
}
