//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_DBT_NEFT_DETAIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSPL_DBT_NEFT_DETAIL()
        {
            this.TSPL_DBT_NEFT_REJECT_DETAIL = new HashSet<TSPL_DBT_NEFT_REJECT_DETAIL>();
            this.TSPL_DBT_NEFT_REJECT_SUCESS = new HashSet<TSPL_DBT_NEFT_REJECT_SUCESS>();
        }
    
        public int PK_Id { get; set; }
        public string Document_Code { get; set; }
        public int Against_MP_Incentive_TR { get; set; }
        public Nullable<int> SNo { get; set; }
        public string Rem_Account_No { get; set; }
        public string Rem_Name { get; set; }
        public string VLC_Uploader_Code { get; set; }
        public string MP_Uploader_Code { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string MP_IFSC_No { get; set; }
        public string MP_Account_No { get; set; }
        public string MP_Name { get; set; }
        public string Transaction { get; set; }
        public string MP_Bank { get; set; }
        public string MP_Mobile_No { get; set; }
    
        public virtual TSPL_DBT_NEFT TSPL_DBT_NEFT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_DBT_NEFT_REJECT_DETAIL> TSPL_DBT_NEFT_REJECT_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_DBT_NEFT_REJECT_SUCESS> TSPL_DBT_NEFT_REJECT_SUCESS { get; set; }
    }
}
