//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_ITEM_COST_MAPPING_HEADS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSPL_ITEM_COST_MAPPING_HEADS()
        {
            this.TSPL_ITEM_COST_MAPPING_DETAIL = new HashSet<TSPL_ITEM_COST_MAPPING_DETAIL>();
            this.TSPL_ITEM_COST_MAPPING_DETAILS_ALL = new HashSet<TSPL_ITEM_COST_MAPPING_DETAILS_ALL>();
            this.TSPL_BOM_OVERHEAD_COST_MAPPING_DETAILS = new HashSet<TSPL_BOM_OVERHEAD_COST_MAPPING_DETAILS>();
        }
    
        public string HCODE { get; set; }
        public System.DateTime DOC_DATE { get; set; }
        public string Item_Code { get; set; }
        public string UOM { get; set; }
        public string GROUP_CODE { get; set; }
        public string Description { get; set; }
        public System.DateTime Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public decimal TOTAL_COST { get; set; }
        public int Status { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Modify_By { get; set; }
        public System.DateTime Modify_Date { get; set; }
        public string Posted_By { get; set; }
        public Nullable<System.DateTime> Posted_Date { get; set; }
        public string Comp_code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_ITEM_COST_MAPPING_DETAIL> TSPL_ITEM_COST_MAPPING_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_ITEM_COST_MAPPING_DETAILS_ALL> TSPL_ITEM_COST_MAPPING_DETAILS_ALL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_BOM_OVERHEAD_COST_MAPPING_DETAILS> TSPL_BOM_OVERHEAD_COST_MAPPING_DETAILS { get; set; }
        public virtual TSPL_OVERHEAD_COST_GROUP_HEAD TSPL_OVERHEAD_COST_GROUP_HEAD { get; set; }
        public virtual TSPL_ITEM_MASTER TSPL_ITEM_MASTER { get; set; }
    }
}
