//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_Dispatch_Detail_BulkSale_History
    {
        public string Document_No { get; set; }
        public string Item_Code { get; set; }
        public string Unit_code { get; set; }
        public double Qty { get; set; }
        public double FatPer { get; set; }
        public double SNFPer { get; set; }
        public double CLR { get; set; }
        public double FatRate { get; set; }
        public double SNFRate { get; set; }
        public double Fat_KG { get; set; }
        public double SNF_KG { get; set; }
        public decimal FatAmount { get; set; }
        public decimal SNFAmount { get; set; }
        public double NetMilkRate { get; set; }
        public decimal Amount { get; set; }
        public double StandardRate { get; set; }
        public string Seal_No { get; set; }
        public string Type { get; set; }
        public string Chamber_Desc { get; set; }
        public string SO_Unit_code { get; set; }
        public double SO_Qty { get; set; }
        public Nullable<double> Qty_in_Ltr { get; set; }
        public string TAX1 { get; set; }
        public Nullable<decimal> TAX1_Base_Amt { get; set; }
        public Nullable<decimal> TAX1_Rate { get; set; }
        public Nullable<decimal> TAX1_Amt { get; set; }
        public string TAX2 { get; set; }
        public Nullable<decimal> TAX2_Base_Amt { get; set; }
        public Nullable<decimal> TAX2_Rate { get; set; }
        public Nullable<decimal> TAX2_Amt { get; set; }
        public string TAX3 { get; set; }
        public Nullable<decimal> TAX3_Base_Amt { get; set; }
        public Nullable<decimal> TAX3_Rate { get; set; }
        public Nullable<decimal> TAX3_Amt { get; set; }
        public string TAX4 { get; set; }
        public Nullable<decimal> TAX4_Base_Amt { get; set; }
        public Nullable<decimal> TAX4_Rate { get; set; }
        public Nullable<decimal> TAX4_Amt { get; set; }
        public string TAX5 { get; set; }
        public Nullable<decimal> TAX5_Base_Amt { get; set; }
        public Nullable<decimal> TAX5_Rate { get; set; }
        public Nullable<decimal> TAX5_Amt { get; set; }
        public Nullable<decimal> Total_Tax_Amt { get; set; }
        public Nullable<decimal> Item_Net_Amt { get; set; }
    }
}
