//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_WH_BREAKAGE_HEAD
    {
        public string Document_No { get; set; }
        public Nullable<System.DateTime> Document_Date { get; set; }
        public Nullable<System.DateTime> Posting_Date { get; set; }
        public Nullable<int> Is_Post { get; set; }
        public string Loc_Code { get; set; }
        public string Loc_Desc { get; set; }
        public string Description { get; set; }
        public string Reference { get; set; }
        public string Comp_Code { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Modified_By { get; set; }
        public System.DateTime Modified_Date { get; set; }
    }
}
