//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_JW_ESTIMATE_HEAD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSPL_JW_ESTIMATE_HEAD()
        {
            this.TSPL_JW_ESTIMATE_DETAILS = new HashSet<TSPL_JW_ESTIMATE_DETAILS>();
        }
    
        public string Document_NO { get; set; }
        public System.DateTime Document_Date { get; set; }
        public string JW_Location { get; set; }
        public string Vendor_Code { get; set; }
        public string Item_Structure { get; set; }
        public string Formula_code { get; set; }
        public System.DateTime Formula_Date { get; set; }
        public string Formula { get; set; }
        public Nullable<decimal> JW_Estimat { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Modified_By { get; set; }
        public System.DateTime Modified_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_JW_ESTIMATE_DETAILS> TSPL_JW_ESTIMATE_DETAILS { get; set; }
        public virtual TSPL_STRUCTURE_MASTER TSPL_STRUCTURE_MASTER { get; set; }
        public virtual TSPL_LOCATION_MASTER TSPL_LOCATION_MASTER { get; set; }
        public virtual TSPL_VENDOR_MASTER TSPL_VENDOR_MASTER { get; set; }
    }
}
