//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_MCC_MILK_TRANSFER_PRICE
    {
        public string Price_Code { get; set; }
        public System.DateTime Price_Date { get; set; }
        public System.DateTime Cost_Calc_From_Date { get; set; }
        public System.DateTime Cost_Calc_To_Date { get; set; }
        public System.DateTime Transfer_Price_From_Date { get; set; }
        public System.DateTime Transfer_Price_To_Date { get; set; }
        public string MCC_Code { get; set; }
        public string Mcc_Name { get; set; }
        public double Milk_Cost { get; set; }
        public double Primary_Transporter_Cost { get; set; }
        public double Chilling_Charge { get; set; }
        public double Mcc_Rent { get; set; }
        public double VSP_Charge { get; set; }
        public double Manpower_Cost { get; set; }
        public double Admin_Cost { get; set; }
        public double Procurement_Cost { get; set; }
        public double Secondary_Transporter_Cost { get; set; }
        public double Head_Cost_Per { get; set; }
        public double Head_Cost { get; set; }
        public double Total_Cost { get; set; }
        public int isPosted { get; set; }
        public Nullable<System.DateTime> Posting_Date { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Modified_By { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public string Comp_Code { get; set; }
    
        public virtual TSPL_COMPANY_MASTER TSPL_COMPANY_MASTER { get; set; }
    }
}
