//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_BOOKING_PAYMENT_MODE_DETAIL
    {
        public string TR_Code { get; set; }
        public string Document_No { get; set; }
        public Nullable<int> SNo { get; set; }
        public string Payment_Mode { get; set; }
        public double Amount { get; set; }
        public string Against_Receipt_No { get; set; }
    
        public virtual TSPL_BOOKING_MATSER TSPL_BOOKING_MATSER { get; set; }
        public virtual TSPL_RECEIPT_HEADER TSPL_RECEIPT_HEADER { get; set; }
    }
}
