//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_SPP_COST_WITHOUT_BATCH
    {
        public string PROD_ENTRY_CODE { get; set; }
        public string Main_ITEM_CODE { get; set; }
        public string BOM_CODE { get; set; }
        public string MAIN_UOM { get; set; }
        public string COST_CODE { get; set; }
        public decimal OverHead_Cost { get; set; }
    
        public virtual TSPL_ITEM_MASTER TSPL_ITEM_MASTER { get; set; }
        public virtual TSPL_SPP_PRODUCTION_ENTRY TSPL_SPP_PRODUCTION_ENTRY { get; set; }
        public virtual TSPL_UNIT_MASTER TSPL_UNIT_MASTER { get; set; }
    }
}
