//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_NOTIFICATIONS_USER_TYPE
    {
        public int PK_Id { get; set; }
        public Nullable<int> SNO { get; set; }
        public string Document_No { get; set; }
        public string Login_Type { get; set; }
    
        public virtual TSPL_NOTIFICATIONS TSPL_NOTIFICATIONS { get; set; }
    }
}
