//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_DOCUMENT_ACCEPTANCE_MT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSPL_DOCUMENT_ACCEPTANCE_MT()
        {
            this.TSPL_DOCUMENT_ACCEPTANCE_DETAIL_MT = new HashSet<TSPL_DOCUMENT_ACCEPTANCE_DETAIL_MT>();
            this.TSPL_EX_COMMERCIAL_INVOICE_HEAD = new HashSet<TSPL_EX_COMMERCIAL_INVOICE_HEAD>();
        }
    
        public string DocumentAcceptanceNo { get; set; }
        public System.DateTime DocumentAcceptance_Date { get; set; }
        public string LCCreationNo { get; set; }
        public string VendorCode { get; set; }
        public string VendorName { get; set; }
        public string Location_Code { get; set; }
        public string Location_Desc { get; set; }
        public decimal LCAmount { get; set; }
        public string ShipmentType { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string ReferenceNo { get; set; }
        public int TrustReceiptLetter { get; set; }
        public int F2Letter { get; set; }
        public int AcceptanceLetter { get; set; }
        public int Posted { get; set; }
        public Nullable<System.DateTime> Posting_Date { get; set; }
        public string Comp_Code { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Modified_By { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public string AcceptanceReferenceNo { get; set; }
        public string PurchaseOrder_No { get; set; }
        public decimal DocumentAmount { get; set; }
        public double Is_Create_Auto_GRN { get; set; }
        public double Is_Create_Auto_MRN { get; set; }
        public double Is_Create_Auto_SRN { get; set; }
        public string GRN_No { get; set; }
        public string MRN_No { get; set; }
        public string SRN_No { get; set; }
        public string PurchaseInvoice_No { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_DOCUMENT_ACCEPTANCE_DETAIL_MT> TSPL_DOCUMENT_ACCEPTANCE_DETAIL_MT { get; set; }
        public virtual TSPL_GRN_HEAD TSPL_GRN_HEAD { get; set; }
        public virtual TSPL_LC_CREATION_MT TSPL_LC_CREATION_MT { get; set; }
        public virtual TSPL_LOCATION_MASTER TSPL_LOCATION_MASTER { get; set; }
        public virtual TSPL_MRN_HEAD TSPL_MRN_HEAD { get; set; }
        public virtual TSPL_PURCHASE_ORDER_HEAD TSPL_PURCHASE_ORDER_HEAD { get; set; }
        public virtual TSPL_EX_PI_HEAD TSPL_EX_PI_HEAD { get; set; }
        public virtual TSPL_SRN_HEAD TSPL_SRN_HEAD { get; set; }
        public virtual TSPL_VENDOR_MASTER TSPL_VENDOR_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_EX_COMMERCIAL_INVOICE_HEAD> TSPL_EX_COMMERCIAL_INVOICE_HEAD { get; set; }
    }
}
