//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_REMITTANCE_ENTRY_DETAIL
    {
        public Nullable<int> SNO { get; set; }
        public string Remittance_Code { get; set; }
        public string Document_No { get; set; }
        public System.DateTime Document_Date { get; set; }
        public string Document_Type { get; set; }
        public Nullable<decimal> Document_Amount { get; set; }
        public string Service_Type { get; set; }
        public Nullable<decimal> Actual_TDS_Base { get; set; }
        public Nullable<decimal> Calculated_TDS_Base { get; set; }
        public Nullable<decimal> Actual_TDS { get; set; }
        public Nullable<decimal> Calculated_TDS { get; set; }
        public Nullable<decimal> Actual_Surcharge { get; set; }
        public Nullable<decimal> Calculated_Surcharge { get; set; }
        public Nullable<decimal> Actual_Edu_Cess { get; set; }
        public Nullable<decimal> Calculated_Edu_Cess { get; set; }
        public Nullable<decimal> Actual_Sec_Educess { get; set; }
        public Nullable<decimal> Calculated_Sec_Educess { get; set; }
        public Nullable<decimal> Actual_Total_TDS { get; set; }
        public Nullable<decimal> Calculated_Total_TDS { get; set; }
        public string Vendor_Code { get; set; }
        public string Vendor_Name { get; set; }
        public Nullable<decimal> TDS_Per { get; set; }
        public Nullable<decimal> Surcharge_Per { get; set; }
        public Nullable<decimal> Edu_Cess_Per { get; set; }
        public Nullable<decimal> Sec_Educess_Per { get; set; }
        public string Fiscal_Year { get; set; }
        public string Quarter { get; set; }
        public string Deduction_Code { get; set; }
    }
}
