//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_MCC_Dispatch_Challan_History
    {
        public string MCC_Code { get; set; }
        public string MCC_Name { get; set; }
        public System.DateTime Dispatch_Date { get; set; }
        public string Chalan_NO { get; set; }
        public string Tanker_Dispatch_To { get; set; }
        public string Mcc_Or_Plant_Code { get; set; }
        public string Tanker_No { get; set; }
        public string Tanker_KM_Reading { get; set; }
        public string Drip_Marking { get; set; }
        public string Tanker_Full { get; set; }
        public string Control_Sample { get; set; }
        public string Name_Of_Custodian { get; set; }
        public string Seal_No1 { get; set; }
        public string Seal_No2 { get; set; }
        public string Seal_No3 { get; set; }
        public string Seal_No4 { get; set; }
        public string Seal_No5 { get; set; }
        public string Seal_No6 { get; set; }
        public string Seal_No7 { get; set; }
        public string Seal_No8 { get; set; }
        public string Seal_No9 { get; set; }
        public string Seal_No10 { get; set; }
        public int isPosted { get; set; }
        public Nullable<System.DateTime> Posting_Date { get; set; }
        public string Item_Code { get; set; }
        public string Item_Desc { get; set; }
        public double Tare_Weight { get; set; }
        public double Gross_Weight { get; set; }
        public double Net_Qty { get; set; }
        public double Transfer_Price { get; set; }
        public string Comp_Code { get; set; }
        public string Modified_By { get; set; }
        public string Modified_Date { get; set; }
        public double control_sample_fat { get; set; }
        public double control_sample_snf { get; set; }
        public string Tanker_Transporter_Name { get; set; }
        public string Payment_Type { get; set; }
        public string Payment_Rate { get; set; }
        public string Charge_For { get; set; }
        public Nullable<double> Payment_Amount { get; set; }
        public string Chemist_code { get; set; }
        public string Chemist_Name { get; set; }
        public string UOM_Code { get; set; }
        public string UOM_desc { get; set; }
        public string Remarks { get; set; }
        public int isReversed { get; set; }
        public string PriceCode { get; set; }
        public Nullable<double> FAT_W { get; set; }
        public Nullable<double> SNF_W { get; set; }
        public Nullable<double> FAT_R { get; set; }
        public Nullable<double> SNF_R { get; set; }
        public Nullable<double> FAT_KG { get; set; }
        public Nullable<double> SNF_KG { get; set; }
        public Nullable<double> FAT_RATE { get; set; }
        public Nullable<double> SNF_RATE { get; set; }
        public Nullable<double> Amount { get; set; }
        public string RefDocType { get; set; }
        public string RefDocNo { get; set; }
        public string Create_By { get; set; }
        public string Created_Date { get; set; }
        public string MCC_Weighment_No { get; set; }
        public Nullable<int> IsAgainstJobWork { get; set; }
        public string Sublocation_Code { get; set; }
        public string GSTStatus { get; set; }
        public Nullable<System.DateTime> Closing_Date { get; set; }
    
        public virtual TSPL_LOCATION_MASTER TSPL_LOCATION_MASTER { get; set; }
        public virtual TSPL_MCC_MASTER TSPL_MCC_MASTER { get; set; }
        public virtual TSPL_TANKER_MASTER TSPL_TANKER_MASTER { get; set; }
    }
}
