//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_JWI_PRICE_HEAD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSPL_JWI_PRICE_HEAD()
        {
            this.TSPL_JOBWORK_BILLING_DETAIL = new HashSet<TSPL_JOBWORK_BILLING_DETAIL>();
            this.TSPL_JWI_PRICE_DETAIL = new HashSet<TSPL_JWI_PRICE_DETAIL>();
            this.TSPL_JWI_PRICE_DETAIL_ALL_UOM = new HashSet<TSPL_JWI_PRICE_DETAIL_ALL_UOM>();
        }
    
        public string Price_Code { get; set; }
        public System.DateTime Price_Date { get; set; }
        public string Description { get; set; }
        public System.DateTime Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public int Posted { get; set; }
        public string Posted_By { get; set; }
        public Nullable<System.DateTime> Posted_Date { get; set; }
        public int Inactive { get; set; }
        public string Inactive_By { get; set; }
        public Nullable<System.DateTime> Inactive_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_JOBWORK_BILLING_DETAIL> TSPL_JOBWORK_BILLING_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_JWI_PRICE_DETAIL> TSPL_JWI_PRICE_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_JWI_PRICE_DETAIL_ALL_UOM> TSPL_JWI_PRICE_DETAIL_ALL_UOM { get; set; }
    }
}
