//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_GATEPASS_DETAIL_PRODUCTSALE
    {
        public string GPCode { get; set; }
        public string Invoice_No { get; set; }
        public System.DateTime Invoice_date { get; set; }
        public string cust_code { get; set; }
        public string Transporter_code { get; set; }
        public string Vehicle_Id { get; set; }
        public Nullable<decimal> Gross_Weight { get; set; }
        public Nullable<decimal> Documnet_Amount { get; set; }
        public Nullable<decimal> Provision_Amount { get; set; }
    
        public virtual TSPL_GATEPASS_MASTER_PRODUCTSALE TSPL_GATEPASS_MASTER_PRODUCTSALE { get; set; }
    }
}
