//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_LC_CREATION_MT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSPL_LC_CREATION_MT()
        {
            this.TSPL_DOCUMENT_ACCEPTANCE_MT = new HashSet<TSPL_DOCUMENT_ACCEPTANCE_MT>();
        }
    
        public string LCCreationNo { get; set; }
        public System.DateTime LCCreation_Date { get; set; }
        public string LCRequestNo { get; set; }
        public string Bank_Code { get; set; }
        public string PurchaseOrder_No { get; set; }
        public string BenefecieryCode { get; set; }
        public decimal LCAmount { get; set; }
        public string LCType { get; set; }
        public double LCPeriod { get; set; }
        public string LCPeriodType { get; set; }
        public int Posted { get; set; }
        public Nullable<System.DateTime> Posting_Date { get; set; }
        public string Comp_Code { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Modified_By { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public string Bank_Name { get; set; }
        public string BenefecieryName { get; set; }
        public string Location_Code { get; set; }
        public string Location_Desc { get; set; }
        public string CURRENCY_CODE { get; set; }
        public double ConvRate { get; set; }
        public Nullable<System.DateTime> LCExpiryDate { get; set; }
        public string ApprovalRequired { get; set; }
        public string Approved { get; set; }
        public string Status { get; set; }
        public double LCCharges { get; set; }
        public string LCCreationType { get; set; }
        public int AbandonmentNo { get; set; }
        public string FDType { get; set; }
        public string FD_No { get; set; }
        public string PurchaseInvoice_No { get; set; }
        public string LCNo { get; set; }
    
        public virtual TSPL_BANK_MASTER TSPL_BANK_MASTER { get; set; }
        public virtual TSPL_CURRENCY_MASTER TSPL_CURRENCY_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_DOCUMENT_ACCEPTANCE_MT> TSPL_DOCUMENT_ACCEPTANCE_MT { get; set; }
        public virtual TSPL_EX_PI_HEAD TSPL_EX_PI_HEAD { get; set; }
        public virtual TSPL_FIXED_DEPOSIT_MASTER_MT TSPL_FIXED_DEPOSIT_MASTER_MT { get; set; }
        public virtual TSPL_VENDOR_MASTER TSPL_VENDOR_MASTER { get; set; }
        public virtual TSPL_LC_REQUEST_MT TSPL_LC_REQUEST_MT { get; set; }
        public virtual TSPL_LOCATION_MASTER TSPL_LOCATION_MASTER { get; set; }
        public virtual TSPL_PURCHASE_ORDER_HEAD TSPL_PURCHASE_ORDER_HEAD { get; set; }
    }
}
