//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_DELIVERY_NOTE_MASTER_FRESHSALE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSPL_DELIVERY_NOTE_MASTER_FRESHSALE()
        {
            this.TSPL_DELIVERY_NOTE_DETAIL_FRESHSALE = new HashSet<TSPL_DELIVERY_NOTE_DETAIL_FRESHSALE>();
            this.TSPL_DISPATCH_MASTER_FRESHSALE = new HashSet<TSPL_DISPATCH_MASTER_FRESHSALE>();
            this.TSPL_SD_SHIPMENT_HEAD = new HashSet<TSPL_SD_SHIPMENT_HEAD>();
            this.TSPL_SD_SHIPMENT_DETAIL = new HashSet<TSPL_SD_SHIPMENT_DETAIL>();
        }
    
        public string Document_No { get; set; }
        public System.DateTime Document_Date { get; set; }
        public int Status { get; set; }
        public string Customer_Code { get; set; }
        public string Location_Code { get; set; }
        public string Booking_No { get; set; }
        public System.DateTime Booking_Date { get; set; }
        public double Vehicle_Capacity { get; set; }
        public string Lorry_No { get; set; }
        public string Road_Permit_No { get; set; }
        public string Transporter_Name { get; set; }
        public string Freight { get; set; }
        public double Freight_Amount { get; set; }
        public int Posted { get; set; }
        public string Comments { get; set; }
        public string Comp_Code { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Modified_By { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public decimal Total_Amt { get; set; }
        public Nullable<System.DateTime> Posting_Date { get; set; }
        public string OnHold { get; set; }
        public string Short_Close { get; set; }
        public string Approval_Reqd { get; set; }
        public string Is_Approved { get; set; }
        public string Price_code { get; set; }
        public string Route_No { get; set; }
        public string CreditApproval_Reqd { get; set; }
        public Nullable<int> Is_Credit_Approved { get; set; }
        public Nullable<System.DateTime> Approved_Date { get; set; }
        public string Approved_By { get; set; }
        public string Approval_Level { get; set; }
        public string Level1_User { get; set; }
        public string Level2_User { get; set; }
        public string Level3_User { get; set; }
        public int Sampling { get; set; }
        public Nullable<int> Is_CustomerChanged { get; set; }
        public string GPCode { get; set; }
        public string TRANSACTION_TYPE { get; set; }
        public string From_Screen_Code { get; set; }
        public string CustPO_No { get; set; }
        public Nullable<System.DateTime> custpo_date { get; set; }
        public string SalesmanCode { get; set; }
        public string Ship_To_Location { get; set; }
        public int isCardSale { get; set; }
    
        public virtual TSPL_BOOKING_MATSER TSPL_BOOKING_MATSER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_DELIVERY_NOTE_DETAIL_FRESHSALE> TSPL_DELIVERY_NOTE_DETAIL_FRESHSALE { get; set; }
        public virtual TSPL_USER_MASTER TSPL_USER_MASTER { get; set; }
        public virtual TSPL_USER_MASTER TSPL_USER_MASTER1 { get; set; }
        public virtual TSPL_USER_MASTER TSPL_USER_MASTER2 { get; set; }
        public virtual TSPL_VEHICLE_MASTER TSPL_VEHICLE_MASTER { get; set; }
        public virtual TSPL_ROUTE_MASTER TSPL_ROUTE_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_DISPATCH_MASTER_FRESHSALE> TSPL_DISPATCH_MASTER_FRESHSALE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_SD_SHIPMENT_HEAD> TSPL_SD_SHIPMENT_HEAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_SD_SHIPMENT_DETAIL> TSPL_SD_SHIPMENT_DETAIL { get; set; }
    }
}
