//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_WH_BREAKAGE_DETAIL
    {
        public string Document_No { get; set; }
        public int Line_No { get; set; }
        public string Item_Code { get; set; }
        public string Item_Description { get; set; }
        public string Unit_Code { get; set; }
        public decimal Item_Quantity { get; set; }
        public decimal Item_Cost { get; set; }
        public decimal mrp { get; set; }
        public Nullable<System.DateTime> MFG_Date { get; set; }
        public Nullable<System.DateTime> Expiry_Date { get; set; }
        public string Breakage { get; set; }
        public Nullable<decimal> Breakage_Qty { get; set; }
        public Nullable<decimal> Leakage_Qty { get; set; }
        public Nullable<decimal> Shortage_Qty { get; set; }
        public string Remarks { get; set; }
    }
}
