//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_AssetIssueReturnDetail
    {
        public string AgainstIssueNo { get; set; }
        public int IsReturn { get; set; }
        public string IssueCode { get; set; }
        public string Asset_Code { get; set; }
        public string Asset_Description { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string Asset_Type_Code { get; set; }
    
        public virtual TSPL_Asset_Details TSPL_Asset_Details { get; set; }
        public virtual TSPL_Asset_Type_Master TSPL_Asset_Type_Master { get; set; }
        public virtual TSPL_AssetIssueReturn TSPL_AssetIssueReturn { get; set; }
    }
}
