//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_DCS_FOR_SALE_FRIEGHT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSPL_DCS_FOR_SALE_FRIEGHT()
        {
            this.TSPL_DCS_FOR_SALE_FRIEGHT_DETAIL = new HashSet<TSPL_DCS_FOR_SALE_FRIEGHT_DETAIL>();
        }
    
        public int PK_ID { get; set; }
        public System.DateTime From_Date { get; set; }
        public Nullable<System.DateTime> To_Date { get; set; }
        public string Description { get; set; }
        public int Inactive { get; set; }
        public string Inactive_By { get; set; }
        public string Location_Code { get; set; }
        public Nullable<System.DateTime> Inactive_Date { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Modified_By { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public int Status { get; set; }
        public string Posted_By { get; set; }
        public Nullable<System.DateTime> Posted_Date { get; set; }
    
        public virtual TSPL_LOCATION_MASTER TSPL_LOCATION_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_DCS_FOR_SALE_FRIEGHT_DETAIL> TSPL_DCS_FOR_SALE_FRIEGHT_DETAIL { get; set; }
    }
}
