//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_HR_TDS_INCOME_TAX_SLAB_DETAIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSPL_HR_TDS_INCOME_TAX_SLAB_DETAIL()
        {
            this.TSPL_HR_TDS_INCOME_TAX_CALCULATION_TAX = new HashSet<TSPL_HR_TDS_INCOME_TAX_CALCULATION_TAX>();
        }
    
        public string TR_Code { get; set; }
        public string Code { get; set; }
        public int SNo { get; set; }
        public decimal From_Range { get; set; }
        public decimal To_Range { get; set; }
        public decimal Taxable_Amt { get; set; }
        public string TAX1 { get; set; }
        public Nullable<decimal> TAX1_Rate { get; set; }
        public string TAX2 { get; set; }
        public Nullable<decimal> TAX2_Rate { get; set; }
        public string TAX3 { get; set; }
        public Nullable<decimal> TAX3_Rate { get; set; }
        public string TAX4 { get; set; }
        public Nullable<decimal> TAX4_Rate { get; set; }
        public string TAX5 { get; set; }
        public Nullable<decimal> TAX5_Rate { get; set; }
        public string TAX6 { get; set; }
        public Nullable<decimal> TAX6_Rate { get; set; }
        public string TAX7 { get; set; }
        public Nullable<decimal> TAX7_Rate { get; set; }
        public string TAX8 { get; set; }
        public Nullable<decimal> TAX8_Rate { get; set; }
        public string TAX9 { get; set; }
        public Nullable<decimal> TAX9_Rate { get; set; }
        public string TAX10 { get; set; }
        public Nullable<decimal> TAX10_Rate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_HR_TDS_INCOME_TAX_CALCULATION_TAX> TSPL_HR_TDS_INCOME_TAX_CALCULATION_TAX { get; set; }
        public virtual TSPL_HR_TDS_INCOME_TAX_SLAB TSPL_HR_TDS_INCOME_TAX_SLAB { get; set; }
    }
}
