//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_MILK_RECEIPT_HEAD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSPL_MILK_RECEIPT_HEAD()
        {
            this.TSPL_MCC_SAMPLE_QC_HEAD = new HashSet<TSPL_MCC_SAMPLE_QC_HEAD>();
            this.TSPL_MILK_RECEIPT_DETAIL = new HashSet<TSPL_MILK_RECEIPT_DETAIL>();
            this.TSPL_MILK_RECEIPT_IMPROPER_WEIGHT_LOG = new HashSet<TSPL_MILK_RECEIPT_IMPROPER_WEIGHT_LOG>();
            this.TSPL_MILK_SAMPLE_HEAD = new HashSet<TSPL_MILK_SAMPLE_HEAD>();
        }
    
        public string DOC_CODE { get; set; }
        public string MCC_CODE { get; set; }
        public System.DateTime DOC_DATE { get; set; }
        public string SHIFT { get; set; }
        public string COMM_PORT { get; set; }
        public string MACHINE_NO { get; set; }
        public decimal TOTAL_WEIGHT { get; set; }
        public decimal FAT { get; set; }
        public decimal SNF { get; set; }
        public decimal Posted { get; set; }
        public Nullable<System.DateTime> Posting_Date { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Modified_By { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public string Comp_Code { get; set; }
        public string Irregular_Mcc_Code { get; set; }
        public Nullable<int> Is_Send_Sms { get; set; }
        public string Dock_Collection_Milk_Type { get; set; }
        public Nullable<int> SYNC_STATUS { get; set; }
        public string DOCK_Code { get; set; }
    
        public virtual TSPL_COMPANY_MASTER TSPL_COMPANY_MASTER { get; set; }
        public virtual TSPL_DOCK_MASTER TSPL_DOCK_MASTER { get; set; }
        public virtual TSPL_MCC_MASTER TSPL_MCC_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MCC_SAMPLE_QC_HEAD> TSPL_MCC_SAMPLE_QC_HEAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MILK_RECEIPT_DETAIL> TSPL_MILK_RECEIPT_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MILK_RECEIPT_IMPROPER_WEIGHT_LOG> TSPL_MILK_RECEIPT_IMPROPER_WEIGHT_LOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSPL_MILK_SAMPLE_HEAD> TSPL_MILK_SAMPLE_HEAD { get; set; }
    }
}
