//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecxPertERPStatusReport.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSPL_SYNC_HOST_SETTINGS
    {
        public int HOST_ID { get; set; }
        public string SERVER_TYPE { get; set; }
        public string SERVER_NAME_IP { get; set; }
        public string DATABASE_NAME { get; set; }
        public string SCHEMA_NAME { get; set; }
        public string DB_USER_ID { get; set; }
        public string DB_PWD { get; set; }
        public string REMARKS { get; set; }
        public bool TEST_CNNECTED_SUCCESS { get; set; }
    }
}
